defmodule QuickTrain.Assets.S3StorageTest do
  use ExUnit.Case, async: false

  alias QuickTrain.Assets.Storage.S3

  @moduletag :storage

  setup_all do
    QuickTrain.S3Fixture.configure()
  end

  setup do
    org = Ash.UUID.generate()
    %{staging: "assets/staging/#{org}/#{Ash.UUID.generate()}", org: org}
  end

  test "descriptor alone uploads capped content and downloads verified opaque bytes", ctx do
    bytes = "<script>opaque</script>"
    expected = facts(bytes, "text/html")
    sealed = sealed(ctx, bytes)
    expiry = DateTime.add(DateTime.utc_now(), 60)
    assert {:ok, upload} = S3.writable_staging_access(ctx.staging, byte_size(bytes), expiry)
    assert upload.method == :post
    assert upload.file_field == "file"
    assert DateTime.compare(upload.expires_at, expiry) in [:lt, :eq]
    refute Map.has_key?(upload.form_fields, "acl")

    assert {:ok, %Req.Response{} = response} =
             S3.HTTPClient.request(
               method: :post,
               url: URI.to_string(upload.uri),
               tls_options: ctx.s3_config.tls_options,
               form_multipart:
                 Map.to_list(upload.form_fields) ++
                   [{upload.file_field, {bytes, filename: "file.html"}}]
             )

    assert response.status in [200, 201, 204]

    assert {:ok, %{sealed_key: ^sealed, facts: ^expected}} =
             S3.verify_and_publish(ctx.staging, sealed, expected, 30_000)

    assert {:ok, ^expected} = S3.verify_sealed(sealed, expected, 30_000)
    assert {:ok, read} = S3.sealed_read_access(sealed, expiry)
    response = Req.get!(ctx.request, url: URI.to_string(read.uri))
    assert response.status == 200
    assert response.body == bytes
    assert Req.Response.get_header(response, "content-type") == ["application/octet-stream"]
    assert Req.Response.get_header(response, "content-disposition") == ["attachment"]
    assert Req.Response.get_header(response, "cache-control") == ["no-store"]

    changed =
      URI.to_string(read.uri) |> String.replace("application%2Foctet-stream", "text%2Fhtml")

    refute changed == URI.to_string(read.uri)
    assert Req.get!(ctx.request, url: changed).status == 403

    {:ok, expired} =
      ExAws.S3.presigned_url(ctx.s3_config.sdk, :get, ctx.s3_config.bucket, sealed,
        expires_in: 1,
        start_datetime: DateTime.add(DateTime.utc_now(), -60),
        query_params:
          URI.decode_query(read.uri.query)
          |> Enum.reject(fn {key, _} -> String.starts_with?(key, "X-Amz-") end)
      )

    assert Req.get!(ctx.request, url: expired).status == 403
  end

  test "generated writes publish long non-ASCII media types and cannot overwrite conflicting facts",
       ctx do
    bytes = "generated bytes"
    media_type = String.duplicate("音声", 2000)
    expected = facts(bytes, media_type)
    sealed = sealed(ctx, bytes)
    assert :ok = S3.write_staging(ctx.staging, ["generated ", "bytes"], 15, 30_000)

    assert {:ok, %{facts: ^expected}} =
             S3.verify_and_publish(ctx.staging, sealed, expected, 30_000)

    assert {:ok, %{facts: ^expected}} =
             S3.verify_and_publish(ctx.staging, sealed, expected, 30_000)

    assert {:error, :canonical_conflict} =
             S3.verify_sealed(sealed, facts(bytes, "text/plain"), 30_000)

    assert :ok = S3.write_staging(ctx.staging, ["different bytes"], 15, 30_000)

    assert {:error, :content_mismatch} =
             S3.verify_and_publish(ctx.staging, sealed, expected, 30_000)

    assert {:ok, ^expected} = S3.verify_sealed(sealed, expected, 30_000)
  end

  test "partial, oversized and blocked enumerables never install staging content", ctx do
    assert {:error, :byte_cap_exceeded} = S3.write_staging(ctx.staging, ["four", "x"], 4, 1_000)

    assert {:error, :storage_write_failed} =
             S3.write_staging(
               ctx.staging,
               Stream.map(["a", "b"], fn
                 "a" -> "a"
                 "b" -> raise "private detail"
               end),
               4,
               1_000
             )

    blocked = Stream.map([1], fn _ -> Process.sleep(:infinity) end)
    start = System.monotonic_time(:millisecond)
    assert {:error, :storage_deadline_exceeded} = S3.write_staging(ctx.staging, blocked, 4, 30)
    assert System.monotonic_time(:millisecond) - start < 1_000

    assert {:error, :staging_missing} =
             S3.verify_and_publish(ctx.staging, sealed(ctx, "a"), facts("a", "text/plain"), 1_000)
  end

  test "maximum-size generated content publishes within the configured operation deadline", ctx do
    config = Application.fetch_env!(:quick_train, :assets)
    cap = Keyword.fetch!(config, :max_bytes)
    budget = Keyword.fetch!(config, :publication_deadline_ms)
    bytes = :binary.copy(<<173>>, cap)
    expected = facts(bytes, "application/octet-stream")
    key = sealed(ctx, bytes)

    chunks =
      Stream.unfold(bytes, fn
        "" -> nil
        <<chunk::binary-size(65_536), rest::binary>> -> {chunk, rest}
        rest -> {rest, ""}
      end)

    started = System.monotonic_time(:millisecond)
    assert :ok = S3.write_staging(ctx.staging, chunks, cap, budget)
    write_ms = System.monotonic_time(:millisecond) - started
    started = System.monotonic_time(:millisecond)
    assert {:ok, %{facts: ^expected}} = S3.verify_and_publish(ctx.staging, key, expected, budget)
    publication_ms = System.monotonic_time(:millisecond) - started
    assert write_ms < budget
    assert publication_ms < budget

    IO.puts(
      "Maximum-size storage transfer: #{cap} bytes; staging #{write_ms} ms; publication #{publication_ms} ms; deadline #{budget} ms per operation"
    )
  end

  test "pre-existing canonical content must have complete matching immutable metadata", ctx do
    bytes = "four"
    key = sealed(ctx, bytes)
    expected = facts(bytes, "text/plain")
    assert :ok = S3.write_staging(ctx.staging, [bytes], 4, 5_000)

    for metadata <- [
          [],
          [{"declared-media-type-sha256", "invalid"}],
          [{"declared-media-type-sha256", String.duplicate("0", 64)}]
        ] do
      # An operator-controlled fixture intentionally seeds malformed canonical facts.
      assert {:ok, _} =
               ExAws.Operation.perform(
                 ExAws.S3.put_object(ctx.s3_config.bucket, key, bytes,
                   content_type: "application/octet-stream",
                   content_disposition: "attachment",
                   cache_control: "no-store",
                   meta: metadata
                 ),
                 ctx.s3_config.sdk
               )

      assert {:error, :canonical_conflict} =
               S3.verify_and_publish(ctx.staging, key, expected, 5_000)
    end
  end

  defp facts(bytes, type),
    do: %{sha256: :crypto.hash(:sha256, bytes), byte_size: byte_size(bytes), media_type: type}

  defp sealed(ctx, bytes),
    do: "assets/sealed/#{ctx.org}/#{Base.encode16(:crypto.hash(:sha256, bytes), case: :lower)}"
end
