defmodule QuickTrain.Repo.Migrations.AuthenticationPersistence do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:sessions, [:revoked_at],
             name: "sessions_revoked_at_index",
             where: "revoked_at IS NOT NULL"
           )

    create index(:sessions, [:expires_at], name: "sessions_expires_at_index")

    alter table(:sessions) do
      remove :organization_id
      remove :token_hash
      add :token_hash, :binary, null: false
    end

    create unique_index(:sessions, [:token_hash], name: "sessions_token_hash_index")

    drop_if_exists unique_index(:oidc_login_transactions, [:state_hash],
                     name: "oidc_login_transactions_state_hash_index"
                   )

    alter table(:oidc_login_transactions) do
      remove :return_to
      remove :state_hash
      add :state_hash, :binary, null: false
      add :nonce_hash, :binary, null: false
      add :redemption_secret_hash, :binary, null: false
      add :callback_key, :text, null: false
      add :callback_uri, :text, null: false
      add :status, :text, null: false, default: "pending"
      add :retain_until, :utc_datetime_usec, null: false
      add :exchange_started_at, :utc_datetime_usec

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:oidc_login_transactions, [:state_hash],
             name: "oidc_login_transactions_state_hash_index"
           )

    create index(:oidc_login_transactions, [:retain_until],
             name: "oidc_login_transactions_retain_until_index"
           )

    create index(:oidc_login_transactions, [:status, :expires_at],
             name: "oidc_login_transactions_status_expires_at_index"
           )

    drop_if_exists unique_index(:external_identities, [:provider, :subject],
                     name: "external_identities_provider_subject_index"
                   )

    drop_if_exists unique_index(:external_identities, [:user_id, :provider],
                     name: "external_identities_user_provider_index"
                   )

    alter table(:external_identities) do
      remove :provider
      add :issuer, :text, null: false
    end

    create unique_index(:external_identities, [:issuer, :subject],
             name: "external_identities_issuer_subject_index"
           )

    create unique_index(:external_identities, [:user_id, :issuer],
             name: "external_identities_user_issuer_index"
           )
  end

  def down do
    raise Ecto.MigrationError,
          "authentication persistence is forward-only; reset a pre-product database or write a replacement-authentication migration"
  end
end
