defmodule QuickTrain.Repo.Migrations.PinExportFormVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:result_exports) do
      add :include_form_context, :boolean, null: false, default: false
    end

    flush()

    # Replace membership only for immutable Forms definitions. The export already
    # pins their version and filters; changing answer/review membership stays intact.
    execute("""
    UPDATE result_exports AS export SET include_form_context = true
    WHERE EXISTS (
      SELECT 1 FROM export_selections AS selection WHERE selection.export_id = export.id
      AND selection.kind IN ('presentation_element', 'question_definition', 'question_option', 'label')
    )
    """)

    execute("""
    DELETE FROM export_selections
    WHERE kind IN ('presentation_element', 'question_definition', 'question_option', 'label')
    """)

    drop_if_exists unique_index(
                     :export_selections,
                     [
                       :export_id,
                       :kind,
                       :task_id,
                       :attempt_id,
                       :question_id,
                       :question_response_id,
                       :decision_id,
                       :presentation_element_id,
                       :question_option_id,
                       :label_id,
                       :binding_id,
                       :dataset_value_id
                     ],
                     name: "export_selections_membership_index"
                   )

    alter table(:export_selections) do
      remove :presentation_element_id
      remove :question_option_id
      remove :label_id
    end

    create unique_index(
             :export_selections,
             [
               :export_id,
               :kind,
               :task_id,
               :attempt_id,
               :question_id,
               :question_response_id,
               :decision_id,
               :binding_id,
               :dataset_value_id
             ],
             name: "export_selections_membership_index",
             nulls_distinct: false
           )
  end

  def down do
    drop_if_exists unique_index(
                     :export_selections,
                     [
                       :export_id,
                       :kind,
                       :task_id,
                       :attempt_id,
                       :question_id,
                       :question_response_id,
                       :decision_id,
                       :binding_id,
                       :dataset_value_id
                     ],
                     name: "export_selections_membership_index"
                   )

    alter table(:export_selections) do
      add :label_id,
          references(:form_labels,
            column: :id,
            with: [form_version_id: :version_id],
            name: "export_selections_label_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :question_option_id,
          references(:form_question_options,
            column: :id,
            with: [question_id: :question_id, form_version_id: :version_id],
            name: "export_selections_question_option_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :presentation_element_id,
          references(:form_presentation_elements,
            column: :id,
            with: [form_version_id: :version_id],
            name: "export_selections_presentation_element_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    create unique_index(
             :export_selections,
             [
               :export_id,
               :kind,
               :task_id,
               :attempt_id,
               :question_id,
               :question_response_id,
               :decision_id,
               :presentation_element_id,
               :question_option_id,
               :label_id,
               :binding_id,
               :dataset_value_id
             ],
             name: "export_selections_membership_index",
             nulls_distinct: false
           )

    flush()

    for {kind, table, owner_fields, owner_values, filter} <- [
          {"presentation_element", "form_presentation_elements", "presentation_element_id",
           "definition.id", "true"},
          {"question_definition", "form_question_definitions", "question_id", "definition.id",
           "true"},
          {"question_option", "form_question_options", "question_id, question_option_id",
           "definition.question_id, definition.id", "true"},
          {"label", "form_labels", "label_id", "definition.id",
           "EXISTS (SELECT 1 FROM form_annotation_constraints AS annotation WHERE annotation.version_id = definition.version_id AND annotation.label_set_id = definition.label_set_id)"}
        ] do
      execute("""
      INSERT INTO export_selections (export_id, organization_id, project_id, form_version_id,
        kind, record_count, #{owner_fields})
      SELECT export.id, export.organization_id, export.project_id, export.form_version_id,
        '#{kind}', 1, #{owner_values}
      FROM result_exports AS export JOIN #{table} AS definition ON definition.version_id = export.form_version_id
      WHERE export.include_form_context AND #{filter}
        AND (export.evidence_kind IS NULL OR export.evidence_kind = '#{kind}')
        AND (export.evidence_id_from IS NULL OR definition.id >= export.evidence_id_from)
        AND (export.evidence_id_to IS NULL OR definition.id <= export.evidence_id_to)
      """)
    end

    alter table(:result_exports) do
      remove :include_form_context
    end
  end
end
