defmodule QuickTrain.Repo.Migrations.DeferBootstrapAndMaintenance do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:oidc_login_transactions) do
      remove :retain_until
    end

    drop_if_exists index(:oidc_login_transactions, [:retain_until],
                     name: "oidc_login_transactions_retain_until_index"
                   )

    drop_if_exists index(:dataset_imports, [:phase, :open_expires_at, :id],
                     name: "dataset_imports_expiry_cursor_index"
                   )

    drop_if_exists index(:sessions, [:expires_at], name: "sessions_expires_at_index")

    drop_if_exists index(:sessions, [:revoked_at], name: "sessions_revoked_at_index")

    alter table(:assets) do
      remove :staging_cleaned_at
      remove :publication_may_finish_at
    end

    drop_if_exists constraint(:assets, :assets_operation_claim_valid)

    alter table(:assets) do
      remove :operation_claim_kind
    end

    create constraint(:assets, :assets_operation_claim_valid,
             check: """
               (operation_claim_id IS NULL AND operation_claim_expires_at IS NULL) OR
             (operation_claim_id IS NOT NULL AND operation_claim_expires_at IS NOT NULL)

             """
           )

    drop_if_exists index(:assets, [:staging_expires_at], name: "assets_staging_cleanup_index")

    drop_if_exists index(:assets, [:operation_claim_expires_at],
                     name: "assets_operation_claim_expiry_index"
                   )
  end

  def down do
    raise Ecto.MigrationError,
      message: "Maintenance metadata was removed. Restore it with a reviewed forward migration."
  end
end
