defmodule QuickTrain.Repo.Migrations.DeriveCollectionState do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tasks) do
      remove :state
    end

    alter table(:task_question_progress) do
      remove :attention
    end
  end

  def down do
    alter table(:task_question_progress) do
      add :attention, :boolean, null: false, default: false
    end

    alter table(:tasks) do
      add :state, :text, null: false, default: "open"
    end
  end
end
