defmodule QuickTrain.Repo.Migrations.StoreBinaryDigests do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:dataset_imports, :dataset_imports_open_fingerprint_format)

    execute """
    ALTER TABLE dataset_imports
    ALTER COLUMN open_fingerprint TYPE bytea
    USING decode(open_fingerprint, 'hex')
    """

    create constraint(:dataset_imports, :dataset_imports_open_fingerprint_format,
             check: """
               octet_length(open_fingerprint) = 32
             """
           )

    drop_if_exists constraint(:dataset_import_rows, :dataset_import_rows_fingerprint_format)

    execute """
    ALTER TABLE dataset_import_rows
    ALTER COLUMN fingerprint TYPE bytea
    USING decode(fingerprint, 'hex')
    """

    create constraint(:dataset_import_rows, :dataset_import_rows_fingerprint_format,
             check: """
               octet_length(fingerprint) = 32
             """
           )

    drop_if_exists constraint(:assets, :assets_sha256_format)

    execute """
    ALTER TABLE assets
    ALTER COLUMN sha256 TYPE bytea
    USING decode(sha256, 'hex')
    """

    create constraint(:assets, :assets_sha256_format,
             check: """
               octet_length(sha256) = 32
             """
           )

    drop_if_exists constraint(:dataset_item_revisions, :dataset_item_revisions_fingerprint_format)

    execute """
    ALTER TABLE dataset_item_revisions
    ALTER COLUMN fingerprint TYPE bytea
    USING decode(fingerprint, 'hex')
    """

    create constraint(:dataset_item_revisions, :dataset_item_revisions_fingerprint_format,
             check: """
               octet_length(fingerprint) = 32
             """
           )
  end

  def down do
    drop_if_exists constraint(:dataset_item_revisions, :dataset_item_revisions_fingerprint_format)

    execute """
    ALTER TABLE dataset_item_revisions
    ALTER COLUMN fingerprint TYPE text
    USING encode(fingerprint, 'hex')
    """

    create constraint(:dataset_item_revisions, :dataset_item_revisions_fingerprint_format,
             check: """
               fingerprint ~ '^[0-9a-f]{64}$'
             """
           )

    drop_if_exists constraint(:assets, :assets_sha256_format)

    execute """
    ALTER TABLE assets
    ALTER COLUMN sha256 TYPE text
    USING encode(sha256, 'hex')
    """

    create constraint(:assets, :assets_sha256_format,
             check: """
               sha256 ~ '^[0-9a-f]{64}$'
             """
           )

    drop_if_exists constraint(:dataset_import_rows, :dataset_import_rows_fingerprint_format)

    execute """
    ALTER TABLE dataset_import_rows
    ALTER COLUMN fingerprint TYPE text
    USING encode(fingerprint, 'hex')
    """

    create constraint(:dataset_import_rows, :dataset_import_rows_fingerprint_format,
             check: """
               fingerprint ~ '^[0-9a-f]{64}$'
             """
           )

    drop_if_exists constraint(:dataset_imports, :dataset_imports_open_fingerprint_format)

    execute """
    ALTER TABLE dataset_imports
    ALTER COLUMN open_fingerprint TYPE text
    USING encode(open_fingerprint, 'hex')
    """

    create constraint(:dataset_imports, :dataset_imports_open_fingerprint_format,
             check: """
               open_fingerprint ~ '^[0-9a-f]{64}$'
             """
           )
  end
end
