defmodule QuickTrain.Repo.Migrations.AddAssets do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state, :text, null: false, default: "pending"
      add :sha256, :text, null: false
      add :byte_size, :bigint, null: false
      add :media_type, :text, null: false
      add :width, :bigint
      add :height, :bigint
      add :staging_key, :text, null: false
      add :sealed_key, :text
      add :staging_expires_at, :utc_datetime_usec, null: false
      add :staging_cleaned_at, :utc_datetime_usec
      add :failure_reason, :text
      add :operation_claim_kind, :text
      add :operation_claim_id, :uuid
      add :operation_claim_expires_at, :utc_datetime_usec
      add :publication_may_finish_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "assets_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ), null: false
    end

    create unique_index(:assets, [:staging_key], name: "assets_staging_key_index")

    alter table(:assets) do
      add :canonical_asset_id, :uuid
    end

    create index(:assets, [:id, :organization_id],
             name: "assets_id_organization_id_index",
             unique: true
           )

    alter table(:assets) do
      modify :canonical_asset_id,
             references(:assets,
               column: :id,
               with: [organization_id: :organization_id],
               name: "assets_canonical_asset_id_organization_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:assets, :assets_sha256_format,
             check: """
               sha256 ~ '^[0-9a-f]{64}$'
             """
           )

    create constraint(:assets, :assets_byte_size_positive,
             check: """
               byte_size > 0
             """
           )

    create constraint(:assets, :assets_image_dimensions_valid,
             check: """
               (width IS NULL AND height IS NULL) OR (width > 0 AND height > 0)
             """
           )

    create constraint(:assets, :assets_state_valid,
             check: """
               state IN ('pending', 'ready', 'failed', 'duplicate_content')
             """
           )

    create constraint(:assets, :assets_lifecycle_facts_valid,
             check: """
               (state = 'pending' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'ready' AND sealed_key IS NOT NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'failed' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NOT NULL) OR
             (state = 'duplicate_content' AND sealed_key IS NULL AND canonical_asset_id IS NOT NULL AND failure_reason = 'duplicate_content')

             """
           )

    create constraint(:assets, :assets_operation_claim_valid,
             check: """
               (operation_claim_kind IS NULL AND operation_claim_id IS NULL AND operation_claim_expires_at IS NULL) OR
             (operation_claim_kind IN ('finalize', 'cleanup') AND operation_claim_id IS NOT NULL AND operation_claim_expires_at IS NOT NULL)

             """
           )

    create index(:assets, [:organization_id, :sha256],
             name: "assets_ready_organization_sha256_index",
             unique: true,
             where: "state = 'ready'"
           )

    create index(:assets, [:sealed_key],
             name: "assets_sealed_key_index",
             unique: true,
             where: "sealed_key IS NOT NULL"
           )

    create index(:assets, [:staging_expires_at],
             name: "assets_staging_cleanup_index",
             where: "staging_cleaned_at IS NULL"
           )

    create index(:assets, [:operation_claim_expires_at],
             name: "assets_operation_claim_expiry_index",
             where: "operation_claim_id IS NOT NULL"
           )
  end

  def down do
    drop_if_exists index(:assets, [:operation_claim_expires_at],
                     name: "assets_operation_claim_expiry_index"
                   )

    drop_if_exists index(:assets, [:staging_expires_at], name: "assets_staging_cleanup_index")

    drop_if_exists index(:assets, [:sealed_key], name: "assets_sealed_key_index")

    drop_if_exists index(:assets, [:organization_id, :sha256],
                     name: "assets_ready_organization_sha256_index"
                   )

    drop_if_exists constraint(:assets, :assets_operation_claim_valid)

    drop_if_exists constraint(:assets, :assets_lifecycle_facts_valid)

    drop_if_exists constraint(:assets, :assets_state_valid)

    drop_if_exists constraint(:assets, :assets_image_dimensions_valid)

    drop_if_exists constraint(:assets, :assets_byte_size_positive)

    drop_if_exists constraint(:assets, :assets_sha256_format)

    drop constraint(:assets, "assets_canonical_asset_id_organization_id_fkey")

    drop constraint(:assets, "assets_organization_id_fkey")

    alter table(:assets) do
      modify :canonical_asset_id, :uuid
    end

    drop_if_exists index(:assets, [:id, :organization_id],
                     name: "assets_id_organization_id_index"
                   )

    alter table(:assets) do
      remove :canonical_asset_id
    end

    drop_if_exists unique_index(:assets, [:staging_key], name: "assets_staging_key_index")

    drop table(:assets)
  end
end
