defmodule QuickTrain.Repo.Migrations.IndexProjectCollectionProgress do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:task_question_progress, [:project_id])

    create index(:task_item_coverage, [:project_id, :project_item_id])
  end

  def down do
    drop_if_exists index(:task_item_coverage, [:project_id, :project_item_id])

    drop_if_exists index(:task_question_progress, [:project_id])
  end
end
