defmodule QuickTrain.Repo.Migrations.AddProjects do
  @moduledoc "Updates resources based on their most recent snapshots.\n\nThis file was autogenerated with `mix ash_postgres.generate_migrations`\n"
  use Ecto.Migration

  def up do
    create(table(:project_items, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :dataset_id,
        references(:datasets,
          column: :id,
          name: "project_items_dataset_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :schema_version_id,
        references(:dataset_schema_versions,
          column: :id,
          with: [dataset_id: :dataset_id],
          name: "project_items_schema_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :item_id,
        references(:dataset_items,
          column: :id,
          name: "project_items_item_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_items, [:project_id, :item_id],
        name: "project_items_project_item_index"
      )
    )

    alter(table(:project_items)) do
      add(:revision_id, :uuid, null: false)
    end

    create(index(:project_items, [:id, :project_id], unique: true))
    create(index(:project_items, [:id, :project_id, :revision_id], unique: true))

    create(table(:project_input_bindings, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :schema_version_id,
        references(:dataset_schema_versions,
          column: :id,
          name: "project_input_bindings_schema_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :root_record_type_id,
        references(:dataset_record_types,
          column: :id,
          with: [schema_version_id: :schema_version_id],
          name: "project_input_bindings_root_record_type_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "project_input_bindings_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :requirement_id,
        references(:form_input_field_requirements,
          column: :id,
          with: [form_version_id: :version_id],
          name: "project_input_bindings_requirement_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_input_bindings, [:project_id, :requirement_id],
        name: "project_input_bindings_project_requirement_index"
      )
    )

    alter(table(:project_input_bindings)) do
      add(
        :field_definition_id,
        references(:dataset_field_definitions,
          column: :id,
          with: [root_record_type_id: :record_type_id],
          name: "project_input_bindings_field_definition_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(index(:project_input_bindings, [:id, :project_id], unique: true))

    create(table(:attempts, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:request_key, :uuid, null: false)
      add(:operation, :text, null: false)
      add(:state, :text, null: false)
      add(:deadline, :utc_datetime_usec, null: false)
      add(:started_at, :utc_datetime_usec)
      add(:terminal_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "attempts_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "attempts_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:task_id, :uuid, null: false)

      add(
        :worker_id,
        references(:users,
          column: :id,
          name: "attempts_worker_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :requester_id,
        references(:users,
          column: :id,
          name: "attempts_requester_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:attempts, [:project_id, :requester_id, :request_key],
        name: "attempts_request_index"
      )
    )

    alter(table(:attempts)) do
      add(:predecessor_id, :uuid)
    end

    create(
      index(:attempts, [:id, :task_id, :project_id, :form_version_id],
        name: "attempts_scope_0",
        unique: true
      )
    )

    create(index(:attempts, [:id, :task_id, :project_id], name: "attempts_scope_1", unique: true))

    alter(table(:attempts)) do
      modify(
        :predecessor_id,
        references(:attempts,
          column: :id,
          with: [project_id: :project_id, task_id: :task_id],
          name: "attempts_predecessor_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(index(:attempts, [:task_id, :state, :deadline], name: "attempts_scope_2"))
    create(index(:attempts, [:project_id, :worker_id, :state], name: "attempts_scope_3"))
    create(index(:attempts, [:task_id, :worker_id], name: "attempts_scope_4"))

    create(table(:task_input_answers, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:position, :bigint)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "task_input_answers_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "task_input_answers_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:task_id, :uuid, null: false)

      add(
        :question_id,
        references(:form_question_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "task_input_answers_question_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:question_response_id, :uuid, null: false)
    end

    create(
      unique_index(:task_input_answers, [:question_response_id, :position],
        name: "task_input_answers_rank_index"
      )
    )

    alter(table(:task_input_answers)) do
      add(:task_input_id, :uuid, null: false)
    end

    create(
      unique_index(:task_input_answers, [:question_response_id, :task_input_id],
        name: "task_input_answers_input_index"
      )
    )

    create(table(:project_question_policies, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:accepted_target, :bigint, null: false)
      add(:skip_allowed, :boolean, null: false, default: false)
      add(:reason_required, :boolean, null: false, default: false)
      add(:failure_threshold, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "project_question_policies_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :question_id,
        references(:form_question_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "project_question_policies_question_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_question_policies, [:project_id, :question_id],
        name: "project_question_policies_project_question_index"
      )
    )

    create(index(:project_question_policies, [:id, :project_id], unique: true))

    create(table(:project_explicit_groups, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:position, :bigint, null: false)
      add(:canonical_key, :binary, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)
    end

    create(
      unique_index(:project_explicit_groups, [:project_id, :canonical_key],
        name: "project_explicit_groups_project_group_index"
      )
    )

    create(
      unique_index(:project_explicit_groups, [:project_id, :position],
        name: "project_explicit_groups_project_position_index"
      )
    )

    alter(table(:project_explicit_groups)) do
      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "project_explicit_groups_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(index(:project_explicit_groups, [:id, :project_id, :form_version_id], unique: true))

    create(table(:text_spans, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:start, :bigint, null: false)
      add(:end, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "text_spans_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "text_spans_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:task_id, :uuid, null: false)

      add(
        :question_id,
        references(:form_question_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "text_spans_question_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:question_response_id, :uuid, null: false)
      add(:task_input_id, :uuid, null: false)

      add(
        :source_value_id,
        references(:dataset_values,
          column: :id,
          name: "text_spans_source_value_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:label_id, :uuid, null: false)
    end

    create(
      unique_index(
        :text_spans,
        [:question_response_id, :task_input_id, :source_value_id, :label_id, :start, :end],
        name: "text_spans_span_index"
      )
    )

    create(table(:project_worker_access, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:disposition, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :user_id,
        references(:users,
          column: :id,
          name: "project_worker_access_user_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_worker_access, [:project_id, :user_id],
        name: "project_worker_access_project_user_index"
      )
    )

    create(index(:project_worker_access, [:id, :project_id], unique: true))
    create(index(:form_question_options, [:id, :question_id, :version_id], unique: true))

    create(table(:task_inputs, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "task_inputs_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "task_inputs_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:task_id, :uuid, null: false)
      add(:project_item_id, :uuid, null: false)
    end

    create(
      unique_index(:task_inputs, [:task_id, :project_item_id],
        name: "task_inputs_task_item_index"
      )
    )

    (
      alter(table(:task_inputs)) do
        add(
          :revision_id,
          references(:dataset_item_revisions,
            column: :id,
            name: "task_inputs_revision_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end

      alter(table(:task_inputs)) do
        modify(
          :project_item_id,
          references(:project_items,
            column: :id,
            with: [project_id: :project_id, revision_id: :revision_id],
            name: "task_inputs_project_item_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:task_inputs)) do
        add(
          :input_slot_id,
          references(:form_input_slot_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "task_inputs_input_slot_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      index(:task_inputs, [:id, :task_id, :project_id, :form_version_id],
        name: "task_inputs_scope_0",
        unique: true
      )
    )

    alter(table(:task_input_answers)) do
      modify(
        :task_input_id,
        references(:task_inputs,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
          name: "task_input_answers_task_input_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:text_spans)) do
      modify(
        :task_input_id,
        references(:task_inputs,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
          name: "text_spans_task_input_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      index(:task_inputs, [:id, :task_id, :input_slot_id],
        name: "task_inputs_scope_1",
        unique: true
      )
    )

    create(index(:forms, [:id, :organization_id], unique: true))

    create(table(:tasks, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:canonical_key, :binary, null: false)
      add(:canonical_membership, :binary, null: false)
      add(:state, :text, null: false, default: "open")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "tasks_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)
    end

    create(
      unique_index(:tasks, [:project_id, :canonical_key], name: "tasks_canonical_group_index")
    )

    alter(table(:tasks)) do
      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "tasks_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :explicit_group_id,
        references(:project_explicit_groups,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "tasks_explicit_group_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      index(:tasks, [:id, :project_id, :form_version_id], name: "tasks_scope_0", unique: true)
    )

    alter(table(:attempts)) do
      modify(
        :task_id,
        references(:tasks,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "attempts_task_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:task_input_answers)) do
      modify(
        :task_id,
        references(:tasks,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "task_input_answers_task_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:text_spans)) do
      modify(
        :task_id,
        references(:tasks,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "text_spans_task_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:task_inputs)) do
      modify(
        :task_id,
        references(:tasks,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "task_inputs_task_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(table(:project_explicit_group_inputs, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "project_explicit_group_inputs_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :group_id,
        references(:project_explicit_groups,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "project_explicit_group_inputs_group_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :project_item_id,
        references(:project_items,
          column: :id,
          with: [project_id: :project_id],
          name: "project_explicit_group_inputs_project_item_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_explicit_group_inputs, [:group_id, :project_item_id],
        name: "project_explicit_group_inputs_group_item_index"
      )
    )

    alter(table(:project_explicit_group_inputs)) do
      add(
        :input_slot_id,
        references(:form_input_slot_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "project_explicit_group_inputs_input_slot_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:project_explicit_group_inputs, [:group_id, :input_slot_id, :position],
        name: "project_explicit_group_inputs_group_slot_position_index"
      )
    )

    create(table(:task_question_progress, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:target, :bigint, null: false)
      add(:failure_threshold, :bigint, null: false)
      add(:accepted, :bigint, null: false, default: 0)
      add(:pending, :bigint, null: false, default: 0)
      add(:skipped, :bigint, null: false, default: 0)
      add(:rejected, :bigint, null: false, default: 0)
      add(:live, :bigint, null: false, default: 0)
      add(:failures, :bigint, null: false, default: 0)
      add(:attention, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "task_question_progress_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "task_question_progress_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :task_id,
        references(:tasks,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id],
          name: "task_question_progress_task_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(
        :question_id,
        references(:form_question_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "task_question_progress_question_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:task_question_progress, [:task_id, :question_id],
        name: "task_question_progress_task_question_index"
      )
    )

    create(table(:projects, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter(table(:project_worker_access)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          name: "project_worker_access_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:project_worker_access, :project_worker_access_disposition_check,
        check: "  disposition IN ('allow', 'block')\n"
      )
    )

    (
      alter(table(:projects)) do
        add(:title, :text, null: false)
        add(:state, :text, null: false, default: "draft")
        add(:audience, :text, null: false, default: "organization_members")
        add(:external_access, :text, null: false, default: "allowlisted")
        add(:selection_mode, :text, null: false, default: "balanced")
        add(:review_mode, :text, null: false, default: "automatic")
        add(:coverage_target, :bigint, null: false, default: 1)
        add(:lease_minutes, :bigint, null: false, default: 30)
        add(:activated_at, :utc_datetime_usec)
        add(:completed_at, :utc_datetime_usec)
        add(:archived_at, :utc_datetime_usec)

        add(:inserted_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")
        )

        add(:updated_at, :utc_datetime_usec,
          null: false,
          default: fragment("(now() AT TIME ZONE 'utc')")
        )

        add(
          :organization_id,
          references(:organizations,
            column: :id,
            name: "projects_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :dataset_id,
          references(:datasets,
            column: :id,
            with: [organization_id: :organization_id],
            name: "projects_dataset_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(:schema_version_id, :uuid, null: false)

        add(
          :root_record_type_id,
          references(:dataset_record_types,
            column: :id,
            with: [schema_version_id: :schema_version_id],
            name: "projects_root_record_type_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end

      alter(table(:projects)) do
        modify(
          :schema_version_id,
          references(:dataset_schema_versions,
            column: :id,
            with: [dataset_id: :dataset_id, root_record_type_id: :root_record_type_id],
            name: "projects_schema_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:projects)) do
        add(
          :form_id,
          references(:forms,
            column: :id,
            with: [organization_id: :organization_id],
            name: "projects_form_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(:form_version_id, :uuid, null: false)
      end
    )

    create(index(:projects, [:id, :organization_id], unique: true))
    create(index(:projects, [:id, :organization_id, :form_version_id], unique: true))

    alter(table(:attempts)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "attempts_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      index(:attempts, [:project_id, :worker_id],
        name: "attempts_one_live_worker",
        unique: true,
        where: "state IN ('claimed', 'assigned', 'in_progress')"
      )
    )

    alter(table(:task_input_answers)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "task_input_answers_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:text_spans)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "text_spans_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:task_inputs)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "task_inputs_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:tasks)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "tasks_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:task_question_progress)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [organization_id: :organization_id, form_version_id: :form_version_id],
          name: "task_question_progress_project_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:task_question_progress, :task_question_progress_counts,
        check:
          "  accepted >= 0 AND pending >= 0 AND skipped >= 0 AND rejected >= 0 AND live >= 0 AND failures >= 0\n"
      )
    )

    create(index(:projects, [:id, :dataset_id, :schema_version_id], unique: true))

    alter(table(:project_items)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [schema_version_id: :schema_version_id, dataset_id: :dataset_id],
          name: "project_items_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      index(:projects, [:id, :schema_version_id, :root_record_type_id, :form_version_id],
        unique: true
      )
    )

    alter(table(:project_input_bindings)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [
            schema_version_id: :schema_version_id,
            form_version_id: :form_version_id,
            root_record_type_id: :root_record_type_id
          ],
          name: "project_input_bindings_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(index(:projects, [:id, :form_version_id], unique: true))

    alter(table(:project_question_policies)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [form_version_id: :form_version_id],
          name: "project_question_policies_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:project_question_policies, :project_question_policies_accepted_target_check,
        check: "  accepted_target BETWEEN 1 AND 2147483647\n"
      )
    )

    create(
      constraint(:project_question_policies, :project_question_policies_failure_threshold_check,
        check: "  failure_threshold BETWEEN 1 AND 2147483647\n"
      )
    )

    alter(table(:project_explicit_groups)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [form_version_id: :form_version_id],
          name: "project_explicit_groups_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:project_explicit_groups, :project_explicit_groups_position_check,
        check: "  position BETWEEN 0 AND 2147483647\n"
      )
    )

    alter(table(:project_explicit_group_inputs)) do
      modify(
        :project_id,
        references(:projects,
          column: :id,
          with: [form_version_id: :form_version_id],
          name: "project_explicit_group_inputs_project_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:project_explicit_group_inputs, :project_explicit_group_inputs_position_check,
        check: "  position BETWEEN 0 AND 2147483647\n"
      )
    )

    create(table(:review_decisions, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:origin, :text, null: false)
      add(:verdict, :text, null: false)
      add(:number, :bigint, null: false)
      add(:request_key, :uuid)
      add(:reason, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "review_decisions_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "review_decisions_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:review_decisions)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "review_decisions_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:review_decisions)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "review_decisions_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :question_id,
          references(:form_question_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "review_decisions_question_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(:question_response_id, :uuid, null: false)
      end
    )

    create(
      unique_index(:review_decisions, [:question_response_id, :number],
        name: "review_decisions_decision_number_index"
      )
    )

    alter(table(:review_decisions)) do
      add(
        :requester_id,
        references(:users,
          column: :id,
          name: "review_decisions_requester_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      unique_index(:review_decisions, [:question_response_id, :requester_id, :request_key],
        name: "review_decisions_request_index"
      )
    )

    alter(table(:review_decisions)) do
      add(:predecessor_id, :uuid)
    end

    create(
      index(:review_decisions, [:id, :question_response_id],
        name: "review_decisions_scope_0",
        unique: true
      )
    )

    alter(table(:review_decisions)) do
      modify(
        :predecessor_id,
        references(:review_decisions,
          column: :id,
          with: [question_response_id: :question_response_id],
          name: "review_decisions_predecessor_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(index(:form_versions, [:id, :form_id], unique: true))

    alter(table(:projects)) do
      modify(
        :form_version_id,
        references(:form_versions,
          column: :id,
          with: [form_id: :form_id],
          name: "projects_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:projects, :projects_state_check,
        check: "  state IN ('draft', 'active', 'paused', 'completed', 'archived')\n"
      )
    )

    create(
      constraint(:projects, :projects_coverage_check,
        check: "  coverage_target BETWEEN 1 AND 2147483647\n"
      )
    )

    create(
      constraint(:projects, :projects_lease_check, check: "  lease_minutes BETWEEN 1 AND 120\n")
    )

    create(
      constraint(:projects, :projects_audience_check,
        check: "  audience IN ('organization_members', 'external_users', 'both')\n"
      )
    )

    create(
      constraint(:projects, :projects_external_access_check,
        check: "  external_access IN ('open', 'allowlisted')\n"
      )
    )

    create(
      constraint(:projects, :projects_selection_check,
        check: "  selection_mode IN ('balanced', 'explicit')\n"
      )
    )

    create(
      constraint(:projects, :projects_review_check,
        check: "  review_mode IN ('automatic', 'manual')\n"
      )
    )

    create(table(:result_exports, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:state, :text, null: false, default: "queued")
      add(:mode, :text, null: false)
      add(:request_key, :uuid, null: false)
      add(:task_id_from, :uuid)
      add(:task_id_to, :uuid)
      add(:evidence_kind, :text)
      add(:evidence_id_from, :uuid)
      add(:evidence_id_to, :uuid)
      add(:snapshot_at, :utc_datetime_usec)
      add(:record_count, :bigint)
      add(:error_code, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "result_exports_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "result_exports_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:result_exports)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "result_exports_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:result_exports)) do
        add(
          :requester_id,
          references(:users,
            column: :id,
            name: "result_exports_requester_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:result_exports, [:project_id, :requester_id, :request_key],
        name: "result_exports_request_index"
      )
    )

    alter(table(:result_exports)) do
      add(
        :asset_id,
        references(:assets,
          column: :id,
          with: [organization_id: :organization_id],
          name: "result_exports_asset_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(table(:task_item_coverage, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:exposures, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "task_item_coverage_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "task_item_coverage_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:task_item_coverage)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "task_item_coverage_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:task_item_coverage)) do
        add(
          :project_item_id,
          references(:project_items,
            column: :id,
            with: [project_id: :project_id],
            name: "task_item_coverage_project_item_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:task_item_coverage, [:project_item_id],
        name: "task_item_coverage_project_item_index"
      )
    )

    create(table(:question_responses, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:outcome, :text, null: false)
      add(:family, :text, null: false)
      add(:text_value, :text)
      add(:integer_value, :bigint)
      add(:decimal_value, :decimal)
      add(:boolean_value, :boolean)
      add(:reason, :text)
      add(:explanation, :text)
      add(:skipped_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "question_responses_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "question_responses_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:question_responses)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "question_responses_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:question_responses)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "question_responses_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(:response_id, :uuid, null: false)

        add(
          :question_id,
          references(:form_question_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "question_responses_question_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:question_responses, [:response_id, :question_id],
        name: "question_responses_response_question_index"
      )
    )

    create(
      index(:question_responses, [:id, :task_id, :project_id, :form_version_id, :question_id],
        name: "question_responses_scope_0",
        unique: true
      )
    )

    alter(table(:task_input_answers)) do
      modify(
        :question_response_id,
        references(:question_responses,
          column: :id,
          with: [
            project_id: :project_id,
            form_version_id: :form_version_id,
            question_id: :question_id,
            task_id: :task_id
          ],
          name: "task_input_answers_question_response_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:text_spans)) do
      modify(
        :question_response_id,
        references(:question_responses,
          column: :id,
          with: [
            project_id: :project_id,
            form_version_id: :form_version_id,
            question_id: :question_id,
            task_id: :task_id
          ],
          name: "text_spans_question_response_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    alter(table(:review_decisions)) do
      modify(
        :question_response_id,
        references(:question_responses,
          column: :id,
          with: [
            project_id: :project_id,
            form_version_id: :form_version_id,
            question_id: :question_id,
            task_id: :task_id
          ],
          name: "review_decisions_question_response_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:review_decisions, :review_decisions_origin,
        check:
          "  (origin = 'human' AND requester_id IS NOT NULL AND request_key IS NOT NULL) OR (origin = 'system' AND requester_id IS NULL AND request_key IS NULL AND verdict = 'accept')\n"
      )
    )

    create(table(:static_option_answers, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "static_option_answers_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "static_option_answers_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:static_option_answers)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "static_option_answers_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:static_option_answers)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "static_option_answers_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :question_id,
          references(:form_question_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "static_option_answers_question_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :question_response_id,
          references(:question_responses,
            column: :id,
            with: [
              project_id: :project_id,
              form_version_id: :form_version_id,
              question_id: :question_id,
              task_id: :task_id
            ],
            name: "static_option_answers_question_response_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :option_id,
          references(:form_question_options,
            column: :id,
            with: [form_version_id: :version_id, question_id: :question_id],
            name: "static_option_answers_option_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:static_option_answers, [:question_response_id, :option_id],
        name: "static_option_answers_option_index"
      )
    )

    create(
      index(:dataset_item_revisions, [:id, :item_id, :dataset_id, :schema_version_id],
        name: "dataset_item_revisions_id_item_dataset_schema_index",
        unique: true
      )
    )

    alter(table(:project_items)) do
      modify(
        :revision_id,
        references(:dataset_item_revisions,
          column: :id,
          with: [
            schema_version_id: :schema_version_id,
            dataset_id: :dataset_id,
            item_id: :item_id
          ],
          name: "project_items_revision_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(table(:attempt_questions, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "attempt_questions_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "attempt_questions_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:attempt_questions)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "attempt_questions_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:attempt_questions)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "attempt_questions_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :attempt_id,
          references(:attempts,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
            name: "attempt_questions_attempt_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :question_id,
          references(:form_question_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "attempt_questions_question_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:attempt_questions, [:attempt_id, :question_id],
        name: "attempt_questions_offered_index"
      )
    )

    create(
      index(:attempt_questions, [:id, :attempt_id, :question_id],
        name: "attempt_questions_scope_0",
        unique: true
      )
    )

    create(table(:responses, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:state, :text, null: false, default: "draft")
      add(:revision, :bigint, null: false, default: 0)
      add(:submitted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "responses_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "responses_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:responses)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "responses_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:responses)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "responses_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :attempt_id,
          references(:attempts,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
            name: "responses_attempt_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(unique_index(:responses, [:attempt_id], name: "responses_attempt_index"))

    create(
      index(:responses, [:id, :task_id, :project_id, :form_version_id],
        name: "responses_scope_0",
        unique: true
      )
    )

    alter(table(:question_responses)) do
      modify(
        :response_id,
        references(:responses,
          column: :id,
          with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
          name: "question_responses_response_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:question_responses, :question_responses_scalar_family,
        check:
          "  (text_value IS NULL OR (outcome = 'answered' AND family = 'text')) AND (integer_value IS NULL OR (outcome = 'answered' AND family = 'integer')) AND (decimal_value IS NULL OR (outcome = 'answered' AND family = 'decimal')) AND (boolean_value IS NULL OR (outcome = 'answered' AND family = 'boolean'))\n"
      )
    )

    create(table(:attempt_input_presentations, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "attempt_input_presentations_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "attempt_input_presentations_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:attempt_input_presentations)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "attempt_input_presentations_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:attempt_input_presentations)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "attempt_input_presentations_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :attempt_id,
          references(:attempts,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
            name: "attempt_input_presentations_attempt_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(:task_input_id, :uuid, null: false)
      end
    )

    create(
      unique_index(:attempt_input_presentations, [:attempt_id, :task_input_id],
        name: "attempt_input_presentations_input_index"
      )
    )

    alter(table(:attempt_input_presentations)) do
      add(
        :input_slot_id,
        references(:form_input_slot_definitions,
          column: :id,
          with: [form_version_id: :version_id],
          name: "attempt_input_presentations_input_slot_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    create(
      unique_index(:attempt_input_presentations, [:attempt_id, :input_slot_id, :position],
        name: "attempt_input_presentations_display_position_index"
      )
    )

    alter(table(:attempt_input_presentations)) do
      modify(
        :task_input_id,
        references(:task_inputs,
          column: :id,
          with: [input_slot_id: :input_slot_id, task_id: :task_id],
          name: "attempt_input_presentations_task_input_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(table(:project_slot_policies, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:item_count, :bigint, null: false)
      add(:shuffle, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "project_slot_policies_form_version_id_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:project_slot_policies)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [form_version_id: :form_version_id],
            name: "project_slot_policies_project_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:project_slot_policies)) do
        add(
          :input_slot_id,
          references(:form_input_slot_definitions,
            column: :id,
            with: [form_version_id: :version_id],
            name: "project_slot_policies_input_slot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(
      unique_index(:project_slot_policies, [:project_id, :input_slot_id],
        name: "project_slot_policies_project_slot_index"
      )
    )

    create(
      constraint(:project_slot_policies, :project_slot_policies_item_count_check,
        check: "  item_count BETWEEN 1 AND 2147483647\n"
      )
    )

    create(index(:project_slot_policies, [:id, :project_id], unique: true))
    create(index(:form_labels, [:id, :version_id], unique: true))

    alter(table(:text_spans)) do
      modify(
        :label_id,
        references(:form_labels,
          column: :id,
          with: [form_version_id: :version_id],
          name: "text_spans_label_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        )
      )
    end

    create(
      constraint(:text_spans, :text_spans_range,
        check: "  \"start\" >= 0 AND \"end\" > \"start\"\n"
      )
    )

    alter(table(:organizations)) do
      modify(:id, :uuid)
    end
  end

  def down do
    drop_if_exists(constraint(:text_spans, :text_spans_range))
    drop(constraint(:text_spans, "text_spans_label_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_source_value_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_task_input_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_question_response_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_question_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_task_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_form_version_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_project_scope_fkey"))
    drop(constraint(:text_spans, "text_spans_organization_scope_fkey"))

    alter(table(:text_spans)) do
      modify(:label_id, :uuid)
    end

    drop_if_exists(index(:form_labels, [:id, :version_id]))
    drop_if_exists(index(:project_slot_policies, [:id, :project_id]))
    drop_if_exists(constraint(:project_slot_policies, :project_slot_policies_item_count_check))
    drop(constraint(:project_slot_policies, "project_slot_policies_input_slot_id_fkey"))
    drop(constraint(:project_slot_policies, "project_slot_policies_form_version_id_fkey"))
    drop(constraint(:project_slot_policies, "project_slot_policies_project_id_fkey"))

    drop_if_exists(
      unique_index(:project_slot_policies, [:project_id, :input_slot_id],
        name: "project_slot_policies_project_slot_index"
      )
    )

    alter(table(:project_slot_policies)) do
      remove(:input_slot_id)
      modify(:project_id, :uuid)
    end

    drop(table(:project_slot_policies))

    drop(
      constraint(
        :attempt_input_presentations,
        "attempt_input_presentations_input_slot_scope_fkey"
      )
    )

    drop(
      constraint(
        :attempt_input_presentations,
        "attempt_input_presentations_task_input_scope_fkey"
      )
    )

    drop(
      constraint(:attempt_input_presentations, "attempt_input_presentations_attempt_scope_fkey")
    )

    drop(constraint(:attempt_input_presentations, "attempt_input_presentations_task_scope_fkey"))

    drop(
      constraint(
        :attempt_input_presentations,
        "attempt_input_presentations_form_version_scope_fkey"
      )
    )

    drop(
      constraint(:attempt_input_presentations, "attempt_input_presentations_project_scope_fkey")
    )

    drop(
      constraint(
        :attempt_input_presentations,
        "attempt_input_presentations_organization_scope_fkey"
      )
    )

    alter(table(:attempt_input_presentations)) do
      modify(:task_input_id, :uuid)
    end

    drop_if_exists(
      unique_index(:attempt_input_presentations, [:attempt_id, :input_slot_id, :position],
        name: "attempt_input_presentations_display_position_index"
      )
    )

    alter(table(:attempt_input_presentations)) do
      remove(:input_slot_id)
    end

    drop_if_exists(
      unique_index(:attempt_input_presentations, [:attempt_id, :task_input_id],
        name: "attempt_input_presentations_input_index"
      )
    )

    alter(table(:attempt_input_presentations)) do
      remove(:task_input_id)
      remove(:attempt_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:attempt_input_presentations))
    drop_if_exists(constraint(:question_responses, :question_responses_scalar_family))
    drop(constraint(:question_responses, "question_responses_question_scope_fkey"))
    drop(constraint(:question_responses, "question_responses_response_scope_fkey"))
    drop(constraint(:question_responses, "question_responses_task_scope_fkey"))
    drop(constraint(:question_responses, "question_responses_form_version_scope_fkey"))
    drop(constraint(:question_responses, "question_responses_project_scope_fkey"))
    drop(constraint(:question_responses, "question_responses_organization_scope_fkey"))

    alter(table(:question_responses)) do
      modify(:response_id, :uuid)
    end

    drop_if_exists(
      index(:responses, [:id, :task_id, :project_id, :form_version_id], name: "responses_scope_0")
    )

    drop(constraint(:responses, "responses_attempt_scope_fkey"))
    drop(constraint(:responses, "responses_task_scope_fkey"))
    drop(constraint(:responses, "responses_form_version_scope_fkey"))
    drop(constraint(:responses, "responses_project_scope_fkey"))
    drop(constraint(:responses, "responses_organization_scope_fkey"))
    drop_if_exists(unique_index(:responses, [:attempt_id], name: "responses_attempt_index"))

    alter(table(:responses)) do
      remove(:attempt_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:responses))

    drop_if_exists(
      index(:attempt_questions, [:id, :attempt_id, :question_id],
        name: "attempt_questions_scope_0"
      )
    )

    drop(constraint(:attempt_questions, "attempt_questions_question_scope_fkey"))
    drop(constraint(:attempt_questions, "attempt_questions_attempt_scope_fkey"))
    drop(constraint(:attempt_questions, "attempt_questions_task_scope_fkey"))
    drop(constraint(:attempt_questions, "attempt_questions_form_version_scope_fkey"))
    drop(constraint(:attempt_questions, "attempt_questions_project_scope_fkey"))
    drop(constraint(:attempt_questions, "attempt_questions_organization_scope_fkey"))

    drop_if_exists(
      unique_index(:attempt_questions, [:attempt_id, :question_id],
        name: "attempt_questions_offered_index"
      )
    )

    alter(table(:attempt_questions)) do
      remove(:question_id)
      remove(:attempt_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:attempt_questions))
    drop(constraint(:project_items, "project_items_revision_id_fkey"))
    drop(constraint(:project_items, "project_items_item_id_fkey"))
    drop(constraint(:project_items, "project_items_schema_version_id_fkey"))
    drop(constraint(:project_items, "project_items_dataset_id_fkey"))
    drop(constraint(:project_items, "project_items_project_id_fkey"))

    alter(table(:project_items)) do
      modify(:revision_id, :uuid)
    end

    drop_if_exists(
      index(:dataset_item_revisions, [:id, :item_id, :dataset_id, :schema_version_id],
        name: "dataset_item_revisions_id_item_dataset_schema_index"
      )
    )

    drop(constraint(:static_option_answers, "static_option_answers_option_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_question_response_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_question_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_task_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_form_version_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_project_scope_fkey"))
    drop(constraint(:static_option_answers, "static_option_answers_organization_scope_fkey"))

    drop_if_exists(
      unique_index(:static_option_answers, [:question_response_id, :option_id],
        name: "static_option_answers_option_index"
      )
    )

    alter(table(:static_option_answers)) do
      remove(:option_id)
      remove(:question_response_id)
      remove(:question_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:static_option_answers))
    drop_if_exists(constraint(:review_decisions, :review_decisions_origin))
    drop(constraint(:review_decisions, "review_decisions_predecessor_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_requester_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_question_response_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_question_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_task_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_form_version_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_project_scope_fkey"))
    drop(constraint(:review_decisions, "review_decisions_organization_scope_fkey"))

    alter(table(:review_decisions)) do
      modify(:question_response_id, :uuid)
    end

    alter(table(:text_spans)) do
      modify(:question_response_id, :uuid)
    end

    drop(constraint(:task_input_answers, "task_input_answers_task_input_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_question_response_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_question_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_task_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_form_version_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_project_scope_fkey"))
    drop(constraint(:task_input_answers, "task_input_answers_organization_scope_fkey"))

    alter(table(:task_input_answers)) do
      modify(:question_response_id, :uuid)
    end

    drop_if_exists(
      index(:question_responses, [:id, :task_id, :project_id, :form_version_id, :question_id],
        name: "question_responses_scope_0"
      )
    )

    drop_if_exists(
      unique_index(:question_responses, [:response_id, :question_id],
        name: "question_responses_response_question_index"
      )
    )

    alter(table(:question_responses)) do
      remove(:question_id)
      remove(:response_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:question_responses))
    drop(constraint(:task_item_coverage, "task_item_coverage_project_item_scope_fkey"))
    drop(constraint(:task_item_coverage, "task_item_coverage_form_version_scope_fkey"))
    drop(constraint(:task_item_coverage, "task_item_coverage_project_scope_fkey"))
    drop(constraint(:task_item_coverage, "task_item_coverage_organization_scope_fkey"))

    drop_if_exists(
      unique_index(:task_item_coverage, [:project_item_id],
        name: "task_item_coverage_project_item_index"
      )
    )

    alter(table(:task_item_coverage)) do
      remove(:project_item_id)
      modify(:project_id, :uuid)
    end

    drop(table(:task_item_coverage))
    drop(constraint(:result_exports, "result_exports_asset_scope_fkey"))
    drop(constraint(:result_exports, "result_exports_requester_scope_fkey"))
    drop(constraint(:result_exports, "result_exports_form_version_scope_fkey"))
    drop(constraint(:result_exports, "result_exports_project_scope_fkey"))
    drop(constraint(:result_exports, "result_exports_organization_scope_fkey"))

    alter(table(:result_exports)) do
      remove(:asset_id)
    end

    drop_if_exists(
      unique_index(:result_exports, [:project_id, :requester_id, :request_key],
        name: "result_exports_request_index"
      )
    )

    alter(table(:result_exports)) do
      remove(:requester_id)
      modify(:project_id, :uuid)
    end

    drop(table(:result_exports))
    drop_if_exists(constraint(:projects, :projects_review_check))
    drop_if_exists(constraint(:projects, :projects_selection_check))
    drop_if_exists(constraint(:projects, :projects_external_access_check))
    drop_if_exists(constraint(:projects, :projects_audience_check))
    drop_if_exists(constraint(:projects, :projects_lease_check))
    drop_if_exists(constraint(:projects, :projects_coverage_check))
    drop_if_exists(constraint(:projects, :projects_state_check))
    drop(constraint(:projects, "projects_form_version_id_fkey"))
    drop(constraint(:projects, "projects_form_id_fkey"))
    drop(constraint(:projects, "projects_root_record_type_id_fkey"))
    drop(constraint(:projects, "projects_schema_version_id_fkey"))
    drop(constraint(:projects, "projects_dataset_id_fkey"))
    drop(constraint(:projects, "projects_organization_id_fkey"))

    alter(table(:projects)) do
      modify(:form_version_id, :uuid)
    end

    drop_if_exists(index(:form_versions, [:id, :form_id]))

    alter(table(:review_decisions)) do
      modify(:predecessor_id, :uuid)
    end

    drop_if_exists(
      index(:review_decisions, [:id, :question_response_id], name: "review_decisions_scope_0")
    )

    alter(table(:review_decisions)) do
      remove(:predecessor_id)
    end

    drop_if_exists(
      unique_index(:review_decisions, [:question_response_id, :requester_id, :request_key],
        name: "review_decisions_request_index"
      )
    )

    alter(table(:review_decisions)) do
      remove(:requester_id)
    end

    drop_if_exists(
      unique_index(:review_decisions, [:question_response_id, :number],
        name: "review_decisions_decision_number_index"
      )
    )

    alter(table(:review_decisions)) do
      remove(:question_response_id)
      remove(:question_id)
      remove(:task_id)
      modify(:project_id, :uuid)
    end

    drop(table(:review_decisions))

    drop_if_exists(
      constraint(:project_explicit_group_inputs, :project_explicit_group_inputs_position_check)
    )

    drop(
      constraint(
        :project_explicit_group_inputs,
        "project_explicit_group_inputs_input_slot_id_fkey"
      )
    )

    drop(
      constraint(
        :project_explicit_group_inputs,
        "project_explicit_group_inputs_project_item_id_fkey"
      )
    )

    drop(
      constraint(:project_explicit_group_inputs, "project_explicit_group_inputs_group_id_fkey")
    )

    drop(
      constraint(
        :project_explicit_group_inputs,
        "project_explicit_group_inputs_form_version_id_fkey"
      )
    )

    drop(
      constraint(:project_explicit_group_inputs, "project_explicit_group_inputs_project_id_fkey")
    )

    alter(table(:project_explicit_group_inputs)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(constraint(:project_explicit_groups, :project_explicit_groups_position_check))
    drop(constraint(:project_explicit_groups, "project_explicit_groups_form_version_id_fkey"))
    drop(constraint(:project_explicit_groups, "project_explicit_groups_project_id_fkey"))

    alter(table(:project_explicit_groups)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(
      constraint(:project_question_policies, :project_question_policies_failure_threshold_check)
    )

    drop_if_exists(
      constraint(:project_question_policies, :project_question_policies_accepted_target_check)
    )

    drop(constraint(:project_question_policies, "project_question_policies_question_id_fkey"))
    drop(constraint(:project_question_policies, "project_question_policies_form_version_id_fkey"))
    drop(constraint(:project_question_policies, "project_question_policies_project_id_fkey"))

    alter(table(:project_question_policies)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(index(:projects, [:id, :form_version_id]))
    drop(constraint(:project_input_bindings, "project_input_bindings_field_definition_id_fkey"))
    drop(constraint(:project_input_bindings, "project_input_bindings_requirement_id_fkey"))
    drop(constraint(:project_input_bindings, "project_input_bindings_form_version_id_fkey"))
    drop(constraint(:project_input_bindings, "project_input_bindings_root_record_type_id_fkey"))
    drop(constraint(:project_input_bindings, "project_input_bindings_schema_version_id_fkey"))
    drop(constraint(:project_input_bindings, "project_input_bindings_project_id_fkey"))

    alter(table(:project_input_bindings)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(
      index(:projects, [:id, :schema_version_id, :root_record_type_id, :form_version_id])
    )

    alter(table(:project_items)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(index(:projects, [:id, :dataset_id, :schema_version_id]))
    drop_if_exists(constraint(:task_question_progress, :task_question_progress_counts))
    drop(constraint(:task_question_progress, "task_question_progress_question_scope_fkey"))
    drop(constraint(:task_question_progress, "task_question_progress_task_scope_fkey"))
    drop(constraint(:task_question_progress, "task_question_progress_form_version_scope_fkey"))
    drop(constraint(:task_question_progress, "task_question_progress_project_scope_fkey"))
    drop(constraint(:task_question_progress, "task_question_progress_organization_scope_fkey"))

    alter(table(:task_question_progress)) do
      modify(:project_id, :uuid)
    end

    drop(constraint(:tasks, "tasks_explicit_group_scope_fkey"))
    drop(constraint(:tasks, "tasks_form_version_scope_fkey"))
    drop(constraint(:tasks, "tasks_project_scope_fkey"))
    drop(constraint(:tasks, "tasks_organization_scope_fkey"))

    alter(table(:tasks)) do
      modify(:project_id, :uuid)
    end

    drop(constraint(:task_inputs, "task_inputs_input_slot_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_revision_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_project_item_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_task_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_form_version_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_project_scope_fkey"))
    drop(constraint(:task_inputs, "task_inputs_organization_scope_fkey"))

    alter(table(:task_inputs)) do
      modify(:project_id, :uuid)
    end

    alter(table(:text_spans)) do
      modify(:project_id, :uuid)
    end

    alter(table(:task_input_answers)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(index(:attempts, [:project_id, :worker_id], name: "attempts_one_live_worker"))
    drop(constraint(:attempts, "attempts_predecessor_scope_fkey"))
    drop(constraint(:attempts, "attempts_requester_scope_fkey"))
    drop(constraint(:attempts, "attempts_worker_scope_fkey"))
    drop(constraint(:attempts, "attempts_task_scope_fkey"))
    drop(constraint(:attempts, "attempts_form_version_scope_fkey"))
    drop(constraint(:attempts, "attempts_project_scope_fkey"))
    drop(constraint(:attempts, "attempts_organization_scope_fkey"))

    alter(table(:attempts)) do
      modify(:project_id, :uuid)
    end

    drop_if_exists(index(:projects, [:id, :organization_id, :form_version_id]))
    drop_if_exists(index(:projects, [:id, :organization_id]))

    alter(table(:projects)) do
      remove(:form_version_id)
      remove(:form_id)
      remove(:root_record_type_id)
      remove(:schema_version_id)
      remove(:dataset_id)
      remove(:organization_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:archived_at)
      remove(:completed_at)
      remove(:activated_at)
      remove(:lease_minutes)
      remove(:coverage_target)
      remove(:review_mode)
      remove(:selection_mode)
      remove(:external_access)
      remove(:audience)
      remove(:state)
      remove(:title)
    end

    drop_if_exists(constraint(:project_worker_access, :project_worker_access_disposition_check))
    drop(constraint(:project_worker_access, "project_worker_access_user_id_fkey"))
    drop(constraint(:project_worker_access, "project_worker_access_project_id_fkey"))

    alter(table(:project_worker_access)) do
      modify(:project_id, :uuid)
    end

    drop(table(:projects))

    drop_if_exists(
      unique_index(:task_question_progress, [:task_id, :question_id],
        name: "task_question_progress_task_question_index"
      )
    )

    drop(table(:task_question_progress))

    drop_if_exists(
      unique_index(:project_explicit_group_inputs, [:group_id, :input_slot_id, :position],
        name: "project_explicit_group_inputs_group_slot_position_index"
      )
    )

    alter(table(:project_explicit_group_inputs)) do
      remove(:input_slot_id)
    end

    drop_if_exists(
      unique_index(:project_explicit_group_inputs, [:group_id, :project_item_id],
        name: "project_explicit_group_inputs_group_item_index"
      )
    )

    drop(table(:project_explicit_group_inputs))

    alter(table(:task_inputs)) do
      modify(:task_id, :uuid)
    end

    alter(table(:text_spans)) do
      modify(:task_id, :uuid)
    end

    alter(table(:task_input_answers)) do
      modify(:task_id, :uuid)
    end

    alter(table(:attempts)) do
      modify(:task_id, :uuid)
    end

    drop_if_exists(index(:tasks, [:id, :project_id, :form_version_id], name: "tasks_scope_0"))

    alter(table(:tasks)) do
      remove(:explicit_group_id)
      remove(:form_version_id)
    end

    drop_if_exists(
      unique_index(:tasks, [:project_id, :canonical_key], name: "tasks_canonical_group_index")
    )

    drop(table(:tasks))
    drop_if_exists(index(:forms, [:id, :organization_id]))

    drop_if_exists(
      index(:task_inputs, [:id, :task_id, :input_slot_id], name: "task_inputs_scope_1")
    )

    alter(table(:text_spans)) do
      modify(:task_input_id, :uuid)
    end

    alter(table(:task_input_answers)) do
      modify(:task_input_id, :uuid)
    end

    drop_if_exists(
      index(:task_inputs, [:id, :task_id, :project_id, :form_version_id],
        name: "task_inputs_scope_0"
      )
    )

    alter(table(:task_inputs)) do
      remove(:input_slot_id)
      modify(:project_item_id, :uuid)
      remove(:revision_id)
    end

    drop_if_exists(
      unique_index(:task_inputs, [:task_id, :project_item_id],
        name: "task_inputs_task_item_index"
      )
    )

    drop(table(:task_inputs))
    drop_if_exists(index(:form_question_options, [:id, :question_id, :version_id]))
    drop_if_exists(index(:project_worker_access, [:id, :project_id]))

    drop_if_exists(
      unique_index(:project_worker_access, [:project_id, :user_id],
        name: "project_worker_access_project_user_index"
      )
    )

    drop(table(:project_worker_access))

    drop_if_exists(
      unique_index(
        :text_spans,
        [:question_response_id, :task_input_id, :source_value_id, :label_id, :start, :end],
        name: "text_spans_span_index"
      )
    )

    drop(table(:text_spans))
    drop_if_exists(index(:project_explicit_groups, [:id, :project_id, :form_version_id]))

    alter(table(:project_explicit_groups)) do
      remove(:form_version_id)
    end

    drop_if_exists(
      unique_index(:project_explicit_groups, [:project_id, :position],
        name: "project_explicit_groups_project_position_index"
      )
    )

    drop_if_exists(
      unique_index(:project_explicit_groups, [:project_id, :canonical_key],
        name: "project_explicit_groups_project_group_index"
      )
    )

    drop(table(:project_explicit_groups))
    drop_if_exists(index(:project_question_policies, [:id, :project_id]))

    drop_if_exists(
      unique_index(:project_question_policies, [:project_id, :question_id],
        name: "project_question_policies_project_question_index"
      )
    )

    drop(table(:project_question_policies))

    drop_if_exists(
      unique_index(:task_input_answers, [:question_response_id, :task_input_id],
        name: "task_input_answers_input_index"
      )
    )

    alter(table(:task_input_answers)) do
      remove(:task_input_id)
    end

    drop_if_exists(
      unique_index(:task_input_answers, [:question_response_id, :position],
        name: "task_input_answers_rank_index"
      )
    )

    drop(table(:task_input_answers))
    drop_if_exists(index(:attempts, [:task_id, :worker_id], name: "attempts_scope_4"))
    drop_if_exists(index(:attempts, [:project_id, :worker_id, :state], name: "attempts_scope_3"))
    drop_if_exists(index(:attempts, [:task_id, :state, :deadline], name: "attempts_scope_2"))

    alter(table(:attempts)) do
      modify(:predecessor_id, :uuid)
    end

    drop_if_exists(index(:attempts, [:id, :task_id, :project_id], name: "attempts_scope_1"))

    drop_if_exists(
      index(:attempts, [:id, :task_id, :project_id, :form_version_id], name: "attempts_scope_0")
    )

    alter(table(:attempts)) do
      remove(:predecessor_id)
    end

    drop_if_exists(
      unique_index(:attempts, [:project_id, :requester_id, :request_key],
        name: "attempts_request_index"
      )
    )

    drop(table(:attempts))
    drop_if_exists(index(:project_input_bindings, [:id, :project_id]))

    alter(table(:project_input_bindings)) do
      remove(:field_definition_id)
    end

    drop_if_exists(
      unique_index(:project_input_bindings, [:project_id, :requirement_id],
        name: "project_input_bindings_project_requirement_index"
      )
    )

    drop(table(:project_input_bindings))
    drop_if_exists(index(:project_items, [:id, :project_id, :revision_id]))
    drop_if_exists(index(:project_items, [:id, :project_id]))

    alter(table(:project_items)) do
      remove(:revision_id)
    end

    drop_if_exists(
      unique_index(:project_items, [:project_id, :item_id],
        name: "project_items_project_item_index"
      )
    )

    drop(table(:project_items))

    alter(table(:directory_users)) do
      modify(:id, :uuid)
    end
  end
end
