defmodule QuickTrain.Repo.Migrations.IndexFormVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create index(:form_bound_values, [:version_id])

    drop_if_exists index(:form_bound_values, [:id, :version_id])

    create index(:form_text_constraints, [:version_id])

    drop_if_exists index(:form_text_constraints, [:id, :version_id])

    create index(:form_instructions, [:version_id])

    drop_if_exists index(:form_instructions, [:id, :version_id])

    create index(:form_question_options, [:version_id])

    drop_if_exists index(:form_question_options, [:id, :version_id])

    create index(:form_integer_constraints, [:version_id])

    drop_if_exists index(:form_integer_constraints, [:id, :version_id])

    create index(:form_question_placements, [:version_id])

    drop_if_exists index(:form_question_placements, [:id, :version_id])

    create index(:form_sections, [:version_id])

    drop_if_exists index(:form_sections, [:id, :version_id])

    create index(:form_headings, [:version_id])

    drop_if_exists index(:form_headings, [:id, :version_id])

    create index(:form_input_field_requirements, [:version_id])

    create index(:form_input_sources, [:version_id])

    drop_if_exists index(:form_input_sources, [:id, :version_id])

    create index(:form_decimal_constraints, [:version_id])

    drop_if_exists index(:form_decimal_constraints, [:id, :version_id])

    create index(:form_annotation_constraints, [:version_id])

    drop_if_exists index(:form_annotation_constraints, [:id, :version_id])

    create index(:form_selection_constraints, [:version_id])

    drop_if_exists index(:form_selection_constraints, [:id, :version_id])

    create index(:form_labels, [:version_id])

    drop_if_exists index(:form_labels, [:id, :version_id])
  end

  def down do
    create index(:form_labels, [:id, :version_id], unique: true)

    drop_if_exists index(:form_labels, [:version_id])

    create index(:form_selection_constraints, [:id, :version_id], unique: true)

    drop_if_exists index(:form_selection_constraints, [:version_id])

    create index(:form_annotation_constraints, [:id, :version_id], unique: true)

    drop_if_exists index(:form_annotation_constraints, [:version_id])

    create index(:form_decimal_constraints, [:id, :version_id], unique: true)

    drop_if_exists index(:form_decimal_constraints, [:version_id])

    create index(:form_input_sources, [:id, :version_id], unique: true)

    drop_if_exists index(:form_input_sources, [:version_id])

    drop_if_exists index(:form_input_field_requirements, [:version_id])

    create index(:form_headings, [:id, :version_id], unique: true)

    drop_if_exists index(:form_headings, [:version_id])

    create index(:form_sections, [:id, :version_id], unique: true)

    drop_if_exists index(:form_sections, [:version_id])

    create index(:form_question_placements, [:id, :version_id], unique: true)

    drop_if_exists index(:form_question_placements, [:version_id])

    create index(:form_integer_constraints, [:id, :version_id], unique: true)

    drop_if_exists index(:form_integer_constraints, [:version_id])

    create index(:form_question_options, [:id, :version_id], unique: true)

    drop_if_exists index(:form_question_options, [:version_id])

    create index(:form_instructions, [:id, :version_id], unique: true)

    drop_if_exists index(:form_instructions, [:version_id])

    create index(:form_text_constraints, [:id, :version_id], unique: true)

    drop_if_exists index(:form_text_constraints, [:version_id])

    create index(:form_bound_values, [:id, :version_id], unique: true)

    drop_if_exists index(:form_bound_values, [:version_id])
  end
end
