defmodule QuickTrain.Repo.Migrations.ConsolidateAttemptAnswers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:question_responses, "question_responses_response_scope_fkey")

    alter table(:attempts) do
      add :revision, :bigint, null: false, default: 0
      add :legacy_response_id, :uuid
    end

    drop_if_exists unique_index(:question_responses, [:response_id, :question_id],
                     name: "question_responses_response_question_index"
                   )

    rename table(:question_responses), :response_id, to: :attempt_id
    flush()

    execute("""
    UPDATE attempts AS attempt SET revision = response.revision, legacy_response_id = response.id
    FROM responses AS response WHERE response.attempt_id = attempt.id
    """)

    execute("""
    UPDATE question_responses AS outcome SET attempt_id = response.attempt_id
    FROM responses AS response WHERE outcome.attempt_id = response.id
    """)

    drop table(:responses)

    create unique_index(:question_responses, [:attempt_id, :question_id],
             name: "question_responses_attempt_question_index"
           )

    alter table(:question_responses) do
      modify :attempt_id,
             references(:attempts,
               column: :id,
               with: [
                 project_id: :project_id,
                 form_version_id: :form_version_id,
                 task_id: :task_id
               ],
               name: "question_responses_attempt_scope_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end

  def down do
    drop constraint(:question_responses, "question_responses_attempt_scope_fkey")

    drop_if_exists unique_index(:question_responses, [:attempt_id, :question_id],
                     name: "question_responses_attempt_question_index"
                   )

    create(table(:responses, primary_key: false)) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:state, :text, null: false, default: "draft")
      add(:revision, :bigint, null: false, default: 0)
      add(:submitted_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :organization_id,
        references(:organizations,
          column: :id,
          name: "responses_organization_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )

      add(:project_id, :uuid, null: false)

      add(
        :form_version_id,
        references(:form_versions,
          column: :id,
          name: "responses_form_version_scope_fkey",
          type: :uuid,
          prefix: "public",
          on_delete: :restrict
        ),
        null: false
      )
    end

    (
      alter(table(:responses)) do
        modify(
          :project_id,
          references(:projects,
            column: :id,
            with: [organization_id: :organization_id, form_version_id: :form_version_id],
            name: "responses_project_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
        )
      end

      alter(table(:responses)) do
        add(
          :task_id,
          references(:tasks,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id],
            name: "responses_task_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )

        add(
          :attempt_id,
          references(:attempts,
            column: :id,
            with: [project_id: :project_id, form_version_id: :form_version_id, task_id: :task_id],
            name: "responses_attempt_scope_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
        )
      end
    )

    create(unique_index(:responses, [:attempt_id], name: "responses_attempt_index"))

    create(
      index(:responses, [:id, :task_id, :project_id, :form_version_id],
        name: "responses_scope_0",
        unique: true
      )
    )

    flush()

    execute("""
    INSERT INTO responses
      (id, state, revision, submitted_at, organization_id, project_id, form_version_id,
       task_id, attempt_id, inserted_at, updated_at)
    SELECT COALESCE(legacy_response_id, id),
      CASE WHEN state = 'submitted' THEN 'submitted' ELSE 'draft' END,
      revision, CASE WHEN state = 'submitted' THEN terminal_at END,
      organization_id, project_id, form_version_id, task_id, id, inserted_at, updated_at
    FROM attempts
    """)

    execute("""
    UPDATE question_responses AS outcome SET attempt_id = response.id
    FROM responses AS response WHERE outcome.attempt_id = response.attempt_id
    """)

    rename table(:question_responses), :attempt_id, to: :response_id

    alter table(:question_responses) do
      modify :response_id,
             references(:responses,
               with: [
                 project_id: :project_id,
                 form_version_id: :form_version_id,
                 task_id: :task_id
               ],
               name: "question_responses_response_scope_fkey",
               type: :uuid,
               on_delete: :restrict
             )
    end

    create unique_index(:question_responses, [:response_id, :question_id],
             name: "question_responses_response_question_index"
           )

    alter table(:attempts) do
      remove :legacy_response_id
      remove :revision
    end
  end
end
