defmodule QuickTrain.Repo.Migrations.SimplifyFormOwnedDetails do
  @moduledoc """
  Moves presentation content and dynamic input references onto their owning records.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:form_presentation_elements) do
      add :text, :text

      add :requirement_id,
          references(:form_input_field_requirements,
            column: :id,
            with: [version_id: :version_id],
            name: "form_presentation_elements_requirement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :question_id,
          references(:form_question_definitions,
            column: :id,
            with: [version_id: :version_id],
            name: "form_presentation_elements_question_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    alter table(:form_question_definitions) do
      add :input_slot_id,
          references(:form_input_slot_definitions,
            column: :id,
            with: [version_id: :version_id],
            name: "form_question_definitions_input_slot_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )

      add :source_requirement_id,
          references(:form_input_field_requirements,
            column: :id,
            with: [version_id: :version_id],
            name: "form_question_definitions_source_requirement_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          )
    end

    # Move authored values before retiring the wrapper tables. Surviving IDs and timestamps stay intact.
    execute """
    UPDATE form_presentation_elements AS element
    SET text = content.text
    FROM form_instructions AS content
    WHERE element.id = content.element_id
    """

    execute """
    UPDATE form_presentation_elements AS element
    SET text = content.text
    FROM form_headings AS content
    WHERE element.id = content.element_id
    """

    execute """
    UPDATE form_presentation_elements AS element
    SET text = content.text
    FROM form_sections AS content
    WHERE element.id = content.element_id
    """

    execute """
    UPDATE form_presentation_elements AS element
    SET requirement_id = content.requirement_id
    FROM form_bound_values AS content
    WHERE element.id = content.element_id
    """

    execute """
    UPDATE form_presentation_elements AS element
    SET question_id = content.question_id
    FROM form_question_placements AS content
    WHERE element.id = content.element_id
    """

    execute """
    UPDATE form_question_definitions AS question
    SET input_slot_id = source.input_slot_id, source_requirement_id = source.source_requirement_id
    FROM form_input_sources AS source
    WHERE question.id = source.question_id
    """

    drop table(:form_bound_values)

    drop table(:form_headings)

    drop table(:form_input_sources)

    drop table(:form_instructions)

    drop table(:form_question_placements)

    drop table(:form_sections)

    drop_if_exists index(:form_presentation_elements, [:id, :version_id])
  end

  def down do
    # Retired wrapper identities are recreated; the element and question identities are preserved.
    create index(:form_presentation_elements, [:id, :version_id], unique: true)

    create table(:form_instructions, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :element_id,
          references(:form_presentation_elements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :text, :text, null: false
    end

    create unique_index(:form_instructions, [:element_id],
             name: "form_instructions_element_index"
           )

    create index(:form_instructions, [:version_id])

    execute """
    INSERT INTO form_instructions (element_id, version_id, text, inserted_at, updated_at)
    SELECT id, version_id, text, inserted_at, updated_at
    FROM form_presentation_elements WHERE kind = 'instruction'
    """

    create table(:form_headings, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :element_id,
          references(:form_presentation_elements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :text, :text, null: false
    end

    create unique_index(:form_headings, [:element_id], name: "form_headings_element_index")
    create index(:form_headings, [:version_id])

    execute """
    INSERT INTO form_headings (element_id, version_id, text, inserted_at, updated_at)
    SELECT id, version_id, text, inserted_at, updated_at
    FROM form_presentation_elements WHERE kind = 'heading'
    """

    create table(:form_sections, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :element_id,
          references(:form_presentation_elements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :text, :text, null: false
    end

    create unique_index(:form_sections, [:element_id], name: "form_sections_element_index")
    create index(:form_sections, [:version_id])

    execute """
    INSERT INTO form_sections (element_id, version_id, text, inserted_at, updated_at)
    SELECT id, version_id, text, inserted_at, updated_at
    FROM form_presentation_elements WHERE kind = 'section'
    """

    create table(:form_bound_values, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :element_id,
          references(:form_presentation_elements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :requirement_id,
          references(:form_input_field_requirements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_bound_values, [:element_id],
             name: "form_bound_values_element_index"
           )

    create index(:form_bound_values, [:version_id])

    execute """
    INSERT INTO form_bound_values (element_id, version_id, requirement_id, inserted_at, updated_at)
    SELECT id, version_id, requirement_id, inserted_at, updated_at
    FROM form_presentation_elements WHERE kind = 'bound_value'
    """

    create table(:form_question_placements, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :element_id,
          references(:form_presentation_elements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :question_id,
          references(:form_question_definitions,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_question_placements, [:element_id],
             name: "form_question_placements_element_index"
           )

    create index(:form_question_placements, [:version_id])

    execute """
    INSERT INTO form_question_placements (element_id, version_id, question_id, inserted_at, updated_at)
    SELECT id, version_id, question_id, inserted_at, updated_at
    FROM form_presentation_elements WHERE kind = 'question'
    """

    create table(:form_input_sources, primary_key: false) do
      add :id, :uuid, primary_key: true, null: false, default: fragment("gen_random_uuid()")

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            type: :uuid,
            on_delete: :restrict
          ),
          null: false

      add :question_id,
          references(:form_question_definitions,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :input_slot_id,
          references(:form_input_slot_definitions,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: false

      add :source_requirement_id,
          references(:form_input_field_requirements,
            type: :uuid,
            with: [version_id: :version_id],
            on_delete: :restrict
          ),
          null: true
    end

    create unique_index(:form_input_sources, [:question_id],
             name: "form_input_sources_question_index"
           )

    create index(:form_input_sources, [:version_id])

    execute """
    INSERT INTO form_input_sources (question_id, version_id, input_slot_id, source_requirement_id, inserted_at, updated_at)
    SELECT id, version_id, input_slot_id, source_requirement_id, inserted_at, updated_at
    FROM form_question_definitions WHERE input_slot_id IS NOT NULL
    """

    drop constraint(
           :form_question_definitions,
           "form_question_definitions_source_requirement_id_fkey"
         )

    drop constraint(:form_question_definitions, "form_question_definitions_input_slot_id_fkey")

    alter table(:form_question_definitions) do
      remove :source_requirement_id
      remove :input_slot_id
    end

    drop constraint(:form_presentation_elements, "form_presentation_elements_question_id_fkey")

    drop constraint(:form_presentation_elements, "form_presentation_elements_requirement_id_fkey")

    alter table(:form_presentation_elements) do
      remove :question_id
      remove :requirement_id
      remove :text
    end
  end
end
