defmodule QuickTrain.Repo.Migrations.InitialDomainFoundations do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workspaces, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :slug, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id, :uuid, null: false
    end

    create unique_index(:workspaces, [:organization_id, :slug],
             name: "workspaces_organization_slug_index"
           )

    create table(:webhook_receipts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :external_id, :text, null: false
      add :payload, :map, null: false
      add :status, :text, null: false, default: "received"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:webhook_receipts, [:provider, :external_id],
             name: "webhook_receipts_provider_external_index"
           )

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :email, :text, null: false
      add :display_name, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_email_index")

    create table(:sessions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :workspace_id, :uuid
      add :authentication_method, :text, null: false, default: "oidc"
      add :token_hash, :text
      add :issued_at, :utc_datetime_usec, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "sessions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:roles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :key, :text, null: false
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:roles, [:organization_id, :key], name: "roles_organization_key_index")

    create table(:role_capabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role_id, :uuid, null: false
      add :capability_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:role_capabilities, [:role_id, :capability_id],
             name: "role_capabilities_role_capability_index"
           )

    create table(:role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :role_id, :uuid, null: false
      add :workspace_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:role_assignments, [:organization_id, :user_id, :role_id, :workspace_id],
             name: "role_assignments_scope_user_role_index",
             nulls_distinct: false
           )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:workspaces) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "workspaces_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:slug], name: "organizations_slug_index")

    create table(:organization_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "organization_memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :user_id,
          references(:users,
            column: :id,
            name: "organization_memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:organization_memberships, [:organization_id, :user_id],
             name: "organization_memberships_organization_user_index"
           )

    create table(:operations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :source, :text, null: false
      add :idempotency_key, :text, null: false
      add :operation, :text, null: false
      add :user_id, :uuid
      add :organization_id, :uuid
      add :status, :text, null: false, default: "started"
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:operations, [:source, :idempotency_key],
             name: "operations_source_idempotency_index"
           )

    create table(:oidc_login_transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :state_hash, :text, null: false
      add :code_verifier, :text, null: false
      add :return_to, :text, null: false, default: "/"
      add :expires_at, :utc_datetime_usec, null: false
      add :consumed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:oidc_login_transactions, [:state_hash],
             name: "oidc_login_transactions_state_hash_index"
           )

    create table(:integration_credentials, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :provider, :text, null: false
      add :name, :text, null: false
      add :secret_reference, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:integration_credentials, [:organization_id, :provider, :name],
             name: "integration_credentials_scope_index"
           )

    create table(:external_references, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid
      add :provider, :text, null: false
      add :external_type, :text, null: false
      add :external_id, :text, null: false
      add :internal_type, :text, null: false
      add :internal_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:external_references, [:provider, :external_type, :external_id],
             name: "external_references_provider_reference_index"
           )

    create table(:external_identities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :provider, :text, null: false
      add :subject, :text, null: false
      add :status, :text, null: false, default: "active"
      add :claims, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "external_identities_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:external_identities, [:provider, :subject],
             name: "external_identities_provider_subject_index"
           )

    create unique_index(:external_identities, [:user_id, :provider],
             name: "external_identities_user_provider_index"
           )

    create table(:external_group_role_mappings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :directory_group_id, :uuid, null: false
      add :role_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:external_group_role_mappings, [:directory_group_id, :role_id],
             name: "external_group_role_mappings_group_role_index"
           )

    create table(:enterprise_connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :organization_id, :uuid, null: false
      add :provider, :text, null: false
      add :external_id, :text, null: false
      add :status, :text, null: false, default: "active"
      add :configuration, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:enterprise_connections, [:provider, :external_id],
             name: "enterprise_connections_provider_external_index"
           )

    create table(:domain_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :topic, :text, null: false
      add :idempotency_key, :text, null: false
      add :payload, :map, null: false
      add :status, :text, null: false, default: "pending"
      add :attempts, :bigint, null: false, default: 0
      add :dispatched_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:domain_events, [:idempotency_key],
             name: "domain_events_idempotency_key_index"
           )

    create table(:directory_users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :connection_id, :uuid, null: false
      add :membership_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :external_id, :text, null: false
      add :status, :text, null: false, default: "active"
      add :profile, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:directory_users, [:connection_id, :external_id],
             name: "directory_users_connection_external_index"
           )

    create table(:directory_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :directory_user_id, :uuid, null: false
      add :directory_group_id, :uuid, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:directory_memberships, [:directory_user_id, :directory_group_id],
             name: "directory_memberships_user_group_index"
           )

    create table(:directory_groups, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :directory_id, :uuid, null: false
      add :external_id, :text, null: false
      add :name, :text, null: false
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:directory_groups, [:directory_id, :external_id],
             name: "directory_groups_directory_external_index"
           )

    create table(:directories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :connection_id, :uuid, null: false
      add :external_id, :text, null: false
      add :status, :text, null: false, default: "active"
      add :last_synced_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:directories, [:connection_id, :external_id],
             name: "directories_connection_external_index"
           )

    create table(:capabilities, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :description, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:capabilities, [:key], name: "capabilities_key_index")

    create table(:authorization_decisions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :capability, :text, null: false
      add :allowed, :boolean, null: false
      add :reason, :text, null: false
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:authentication_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :user_id, :uuid
      add :organization_id, :uuid
      add :event, :text, null: false
      add :result, :text, null: false
      add :reason, :text
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:audit_records, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :action, :text, null: false
      add :subject_type, :text, null: false
      add :subject_id, :uuid, null: false
      add :actor_user_id, :uuid
      add :organization_id, :uuid
      add :metadata, :map, null: false, default: %{}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:audit_records)

    drop table(:authentication_events)

    drop table(:authorization_decisions)

    drop_if_exists unique_index(:capabilities, [:key], name: "capabilities_key_index")

    drop table(:capabilities)

    drop_if_exists unique_index(:directories, [:connection_id, :external_id],
                     name: "directories_connection_external_index"
                   )

    drop table(:directories)

    drop_if_exists unique_index(:directory_groups, [:directory_id, :external_id],
                     name: "directory_groups_directory_external_index"
                   )

    drop table(:directory_groups)

    drop_if_exists unique_index(:directory_memberships, [:directory_user_id, :directory_group_id],
                     name: "directory_memberships_user_group_index"
                   )

    drop table(:directory_memberships)

    drop_if_exists unique_index(:directory_users, [:connection_id, :external_id],
                     name: "directory_users_connection_external_index"
                   )

    drop table(:directory_users)

    drop_if_exists unique_index(:domain_events, [:idempotency_key],
                     name: "domain_events_idempotency_key_index"
                   )

    drop table(:domain_events)

    drop_if_exists unique_index(:enterprise_connections, [:provider, :external_id],
                     name: "enterprise_connections_provider_external_index"
                   )

    drop table(:enterprise_connections)

    drop_if_exists unique_index(:external_group_role_mappings, [:directory_group_id, :role_id],
                     name: "external_group_role_mappings_group_role_index"
                   )

    drop table(:external_group_role_mappings)

    drop constraint(:external_identities, "external_identities_user_id_fkey")

    drop_if_exists unique_index(:external_identities, [:user_id, :provider],
                     name: "external_identities_user_provider_index"
                   )

    drop_if_exists unique_index(:external_identities, [:provider, :subject],
                     name: "external_identities_provider_subject_index"
                   )

    drop table(:external_identities)

    drop_if_exists unique_index(:external_references, [:provider, :external_type, :external_id],
                     name: "external_references_provider_reference_index"
                   )

    drop table(:external_references)

    drop_if_exists unique_index(:integration_credentials, [:organization_id, :provider, :name],
                     name: "integration_credentials_scope_index"
                   )

    drop table(:integration_credentials)

    drop_if_exists unique_index(:oidc_login_transactions, [:state_hash],
                     name: "oidc_login_transactions_state_hash_index"
                   )

    drop table(:oidc_login_transactions)

    drop_if_exists unique_index(:operations, [:source, :idempotency_key],
                     name: "operations_source_idempotency_index"
                   )

    drop table(:operations)

    drop constraint(:organization_memberships, "organization_memberships_organization_id_fkey")

    drop constraint(:organization_memberships, "organization_memberships_user_id_fkey")

    drop_if_exists unique_index(:organization_memberships, [:organization_id, :user_id],
                     name: "organization_memberships_organization_user_index"
                   )

    drop table(:organization_memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_slug_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :slug
      remove :name
    end

    drop constraint(:workspaces, "workspaces_organization_id_fkey")

    alter table(:workspaces) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop_if_exists unique_index(
                     :role_assignments,
                     [:organization_id, :user_id, :role_id, :workspace_id],
                     name: "role_assignments_scope_user_role_index"
                   )

    drop table(:role_assignments)

    drop_if_exists unique_index(:role_capabilities, [:role_id, :capability_id],
                     name: "role_capabilities_role_capability_index"
                   )

    drop table(:role_capabilities)

    drop_if_exists unique_index(:roles, [:organization_id, :key],
                     name: "roles_organization_key_index"
                   )

    drop table(:roles)

    drop constraint(:sessions, "sessions_user_id_fkey")

    drop table(:sessions)

    drop_if_exists unique_index(:users, [:email], name: "users_email_index")

    drop table(:users)

    drop_if_exists unique_index(:webhook_receipts, [:provider, :external_id],
                     name: "webhook_receipts_provider_external_index"
                   )

    drop table(:webhook_receipts)

    drop_if_exists unique_index(:workspaces, [:organization_id, :slug],
                     name: "workspaces_organization_slug_index"
                   )

    drop table(:workspaces)
  end
end
