defmodule QuickTrain.Repo.Migrations.CascadeExplicitGroupInputs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:project_explicit_group_inputs, "project_explicit_group_inputs_group_id_fkey")

    alter table(:project_explicit_group_inputs) do
      modify :group_id,
             references(:project_explicit_groups,
               column: :id,
               with: [project_id: :project_id, form_version_id: :form_version_id],
               name: "project_explicit_group_inputs_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end
  end

  def down do
    drop constraint(:project_explicit_group_inputs, "project_explicit_group_inputs_group_id_fkey")

    alter table(:project_explicit_group_inputs) do
      modify :group_id,
             references(:project_explicit_groups,
               column: :id,
               with: [project_id: :project_id, form_version_id: :form_version_id],
               name: "project_explicit_group_inputs_group_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end
  end
end
