defmodule QuickTrain.Repo.Migrations.NativePostgresEnums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  alias QuickTrain.Assets.AssetState

  alias QuickTrain.Datasets.{
    DatasetFieldDefinition,
    DatasetImport,
    DatasetImportRow,
    DatasetSchemaVersion,
    DatasetValue
  }

  def up do
    create_enums()

    drop_if_exists constraint(:dataset_imports, :dataset_imports_phase_valid)
    drop_if_exists constraint(:dataset_imports, :dataset_imports_phase_facts_valid)

    drop_if_exists index(:dataset_imports, [:phase, :open_expires_at, :id],
                     name: "dataset_imports_expiry_cursor_index"
                   )

    execute """
    ALTER TABLE dataset_imports
    ALTER COLUMN phase DROP DEFAULT,
    ALTER COLUMN phase TYPE dataset_import_phase USING phase::text::dataset_import_phase,
    ALTER COLUMN phase SET DEFAULT 'open'
    """

    create constraint(:dataset_imports, :dataset_imports_phase_facts_valid,
             check: """
               (phase = 'open' AND sealed_at IS NULL) OR (phase = 'sealed' AND sealed_at IS NOT NULL)
             """
           )

    create index(:dataset_imports, [:phase, :open_expires_at, :id],
             name: "dataset_imports_expiry_cursor_index"
           )

    drop_if_exists constraint(:dataset_import_rows, :dataset_import_rows_outcome_valid)
    drop_if_exists constraint(:dataset_import_rows, :dataset_import_rows_outcome_facts_valid)

    drop_if_exists index(:dataset_import_rows, [:import_id, :outcome, :source_position, :id],
                     name: "dataset_import_rows_outcome_cursor_index"
                   )

    execute """
    ALTER TABLE dataset_import_rows
    ALTER COLUMN outcome DROP DEFAULT,
    ALTER COLUMN outcome TYPE dataset_import_row_outcome USING outcome::text::dataset_import_row_outcome,
    ALTER COLUMN outcome SET DEFAULT 'pending'
    """

    create constraint(:dataset_import_rows, :dataset_import_rows_outcome_facts_valid,
             check: """
               (outcome = 'pending' AND candidate_record_id IS NOT NULL AND item_revision_id IS NULL AND error_code IS NULL) OR (outcome IN ('succeeded', 'unchanged') AND candidate_record_id IS NOT NULL AND item_revision_id IS NOT NULL AND error_code IS NULL) OR (outcome = 'failed' AND item_revision_id IS NULL AND error_code IS NOT NULL)
             """
           )

    create index(:dataset_import_rows, [:import_id, :outcome, :source_position, :id],
             name: "dataset_import_rows_outcome_cursor_index"
           )

    drop_if_exists constraint(:assets, :assets_state_valid)
    drop_if_exists constraint(:assets, :assets_lifecycle_facts_valid)

    drop_if_exists index(:assets, [:organization_id, :sha256],
                     name: "assets_ready_organization_sha256_index"
                   )

    execute """
    ALTER TABLE assets
    ALTER COLUMN state DROP DEFAULT,
    ALTER COLUMN state TYPE asset_state USING state::text::asset_state,
    ALTER COLUMN state SET DEFAULT 'pending'
    """

    create constraint(:assets, :assets_lifecycle_facts_valid,
             check: """
               (state = 'pending' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'ready' AND sealed_key IS NOT NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'failed' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NOT NULL) OR
             (state = 'duplicate_content' AND sealed_key IS NULL AND canonical_asset_id IS NOT NULL AND failure_reason = 'duplicate_content')

             """
           )

    create index(:assets, [:organization_id, :sha256],
             name: "assets_ready_organization_sha256_index",
             unique: true,
             where: "state = 'ready'"
           )

    drop_if_exists constraint(
                     :dataset_field_definitions,
                     :dataset_field_definitions_value_family_valid
                   )

    drop_if_exists constraint(
                     :dataset_field_definitions,
                     :dataset_field_definitions_cardinality_valid
                   )

    execute """
    ALTER TABLE dataset_field_definitions
    ALTER COLUMN value_family TYPE dataset_value_family USING value_family::text::dataset_value_family,
    ALTER COLUMN cardinality DROP DEFAULT,
    ALTER COLUMN cardinality TYPE dataset_field_cardinality USING cardinality::text::dataset_field_cardinality,
    ALTER COLUMN cardinality SET DEFAULT 'single'
    """

    drop_if_exists constraint(:dataset_schema_versions, :dataset_schema_versions_state_valid)

    drop_if_exists constraint(
                     :dataset_schema_versions,
                     :dataset_schema_versions_publication_facts_valid
                   )

    drop_if_exists index(:dataset_schema_versions, [:dataset_id, :state],
                     name: "dataset_schema_versions_dataset_state_index"
                   )

    execute """
    ALTER TABLE dataset_schema_versions
    ALTER COLUMN state DROP DEFAULT,
    ALTER COLUMN state TYPE dataset_schema_version_state USING state::text::dataset_schema_version_state,
    ALTER COLUMN state SET DEFAULT 'draft'
    """

    create constraint(
             :dataset_schema_versions,
             :dataset_schema_versions_publication_facts_valid,
             check: """
               (state = 'draft' AND published_at IS NULL) OR (state = 'published' AND published_at IS NOT NULL AND root_record_type_id IS NOT NULL)
             """
           )

    create index(:dataset_schema_versions, [:dataset_id, :state],
             name: "dataset_schema_versions_dataset_state_index"
           )
  end

  def down do
    drop_if_exists constraint(
                     :dataset_schema_versions,
                     :dataset_schema_versions_publication_facts_valid
                   )

    drop_if_exists index(:dataset_schema_versions, [:dataset_id, :state],
                     name: "dataset_schema_versions_dataset_state_index"
                   )

    execute """
    ALTER TABLE dataset_schema_versions
    ALTER COLUMN state DROP DEFAULT,
    ALTER COLUMN state TYPE text USING state::text,
    ALTER COLUMN state SET DEFAULT 'draft'
    """

    create constraint(
             :dataset_schema_versions,
             :dataset_schema_versions_publication_facts_valid,
             check: """
               (state = 'draft' AND published_at IS NULL) OR (state = 'published' AND published_at IS NOT NULL AND root_record_type_id IS NOT NULL)
             """
           )

    create index(:dataset_schema_versions, [:dataset_id, :state],
             name: "dataset_schema_versions_dataset_state_index"
           )

    create constraint(:dataset_schema_versions, :dataset_schema_versions_state_valid,
             check: """
               state IN ('draft', 'published')
             """
           )

    execute """
    ALTER TABLE dataset_field_definitions
    ALTER COLUMN cardinality DROP DEFAULT,
    ALTER COLUMN cardinality TYPE text USING cardinality::text,
    ALTER COLUMN cardinality SET DEFAULT 'single',
    ALTER COLUMN value_family TYPE text USING value_family::text
    """

    create constraint(:dataset_field_definitions, :dataset_field_definitions_cardinality_valid,
             check: """
               cardinality = 'single'
             """
           )

    create constraint(:dataset_field_definitions, :dataset_field_definitions_value_family_valid,
             check: """
               value_family IN ('text', 'integer', 'decimal', 'boolean', 'utc_datetime', 'asset')
             """
           )

    drop_if_exists constraint(:assets, :assets_lifecycle_facts_valid)

    drop_if_exists index(:assets, [:organization_id, :sha256],
                     name: "assets_ready_organization_sha256_index"
                   )

    execute """
    ALTER TABLE assets
    ALTER COLUMN state DROP DEFAULT,
    ALTER COLUMN state TYPE text USING state::text,
    ALTER COLUMN state SET DEFAULT 'pending'
    """

    create constraint(:assets, :assets_lifecycle_facts_valid,
             check: """
               (state = 'pending' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'ready' AND sealed_key IS NOT NULL AND canonical_asset_id IS NULL AND failure_reason IS NULL) OR
             (state = 'failed' AND sealed_key IS NULL AND canonical_asset_id IS NULL AND failure_reason IS NOT NULL) OR
             (state = 'duplicate_content' AND sealed_key IS NULL AND canonical_asset_id IS NOT NULL AND failure_reason = 'duplicate_content')

             """
           )

    create index(:assets, [:organization_id, :sha256],
             name: "assets_ready_organization_sha256_index",
             unique: true,
             where: "state = 'ready'"
           )

    create constraint(:assets, :assets_state_valid,
             check: """
               state IN ('pending', 'ready', 'failed', 'duplicate_content')
             """
           )

    drop_if_exists constraint(:dataset_import_rows, :dataset_import_rows_outcome_facts_valid)

    drop_if_exists index(:dataset_import_rows, [:import_id, :outcome, :source_position, :id],
                     name: "dataset_import_rows_outcome_cursor_index"
                   )

    execute """
    ALTER TABLE dataset_import_rows
    ALTER COLUMN outcome DROP DEFAULT,
    ALTER COLUMN outcome TYPE text USING outcome::text,
    ALTER COLUMN outcome SET DEFAULT 'pending'
    """

    create constraint(:dataset_import_rows, :dataset_import_rows_outcome_facts_valid,
             check: """
               (outcome = 'pending' AND candidate_record_id IS NOT NULL AND item_revision_id IS NULL AND error_code IS NULL) OR (outcome IN ('succeeded', 'unchanged') AND candidate_record_id IS NOT NULL AND item_revision_id IS NOT NULL AND error_code IS NULL) OR (outcome = 'failed' AND item_revision_id IS NULL AND error_code IS NOT NULL)
             """
           )

    create index(:dataset_import_rows, [:import_id, :outcome, :source_position, :id],
             name: "dataset_import_rows_outcome_cursor_index"
           )

    create constraint(:dataset_import_rows, :dataset_import_rows_outcome_valid,
             check: """
               outcome IN ('pending', 'succeeded', 'unchanged', 'failed')
             """
           )

    drop_if_exists constraint(:dataset_imports, :dataset_imports_phase_facts_valid)

    drop_if_exists index(:dataset_imports, [:phase, :open_expires_at, :id],
                     name: "dataset_imports_expiry_cursor_index"
                   )

    execute """
    ALTER TABLE dataset_imports
    ALTER COLUMN phase DROP DEFAULT,
    ALTER COLUMN phase TYPE text USING phase::text,
    ALTER COLUMN phase SET DEFAULT 'open'
    """

    create constraint(:dataset_imports, :dataset_imports_phase_facts_valid,
             check: """
               (phase = 'open' AND sealed_at IS NULL) OR (phase = 'sealed' AND sealed_at IS NOT NULL)
             """
           )

    create index(:dataset_imports, [:phase, :open_expires_at, :id],
             name: "dataset_imports_expiry_cursor_index"
           )

    create constraint(:dataset_imports, :dataset_imports_phase_valid,
             check: """
               phase IN ('open', 'sealed')
             """
           )

    drop_enums()
  end

  defp create_enums do
    AshPostgres.Migration.create_enum(AssetState)
    AshPostgres.Migration.create_enum(DatasetValue.Family)
    AshPostgres.Migration.create_enum(DatasetFieldDefinition.Cardinality)
    AshPostgres.Migration.create_enum(DatasetImport.Phase)
    AshPostgres.Migration.create_enum(DatasetImportRow.Outcome)
    AshPostgres.Migration.create_enum(DatasetSchemaVersion.State)
  end

  defp drop_enums do
    AshPostgres.Migration.drop_enum(DatasetSchemaVersion.State)
    AshPostgres.Migration.drop_enum(DatasetImportRow.Outcome)
    AshPostgres.Migration.drop_enum(DatasetImport.Phase)
    AshPostgres.Migration.drop_enum(DatasetFieldDefinition.Cardinality)
    AshPostgres.Migration.drop_enum(DatasetValue.Family)
    AshPostgres.Migration.drop_enum(AssetState)
  end
end
