defmodule QuickTrain.Repo.Migrations.MoveCollectionRulesToAsh do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists constraint(:export_selections, :export_selections_typed_owner)

    drop_if_exists constraint(:review_decisions, :review_decisions_origin)

    drop_if_exists constraint(:question_responses, :question_responses_scalar_family)
  end

  def down do
    create constraint(:question_responses, :question_responses_scalar_family,
             check: """
               (text_value IS NULL OR (outcome = 'answered' AND family = 'text')) AND (integer_value IS NULL OR (outcome = 'answered' AND family = 'integer')) AND (decimal_value IS NULL OR (outcome = 'answered' AND family = 'decimal')) AND (boolean_value IS NULL OR (outcome = 'answered' AND family = 'boolean'))
             """
           )

    create constraint(:review_decisions, :review_decisions_origin,
             check: """
               (origin = 'human' AND requester_id IS NOT NULL AND request_key IS NOT NULL) OR (origin = 'system' AND requester_id IS NULL AND request_key IS NULL AND verdict = 'accept')
             """
           )

    create constraint(:export_selections, :export_selections_typed_owner,
             check: """
                 (kind IN ('task','task_input') AND task_id IS NOT NULL AND num_nonnulls(attempt_id,question_id,question_response_id,decision_id,presentation_element_id,question_option_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind IN ('attempt','attempt_question','attempt_input_presentation') AND task_id IS NOT NULL AND attempt_id IS NOT NULL AND num_nonnulls(question_id,question_response_id,decision_id,presentation_element_id,question_option_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind IN ('question_response','static_option_answer','task_input_answer','text_span','review_decision') AND task_id IS NOT NULL AND question_id IS NOT NULL AND question_response_id IS NOT NULL AND (kind != 'review_decision' OR decision_id IS NOT NULL) AND num_nonnulls(attempt_id,presentation_element_id,question_option_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind = 'presentation_element' AND presentation_element_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_id,question_response_id,decision_id,question_option_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind = 'question_definition' AND question_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_response_id,decision_id,presentation_element_id,question_option_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind = 'question_option' AND question_id IS NOT NULL AND question_option_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_response_id,decision_id,presentation_element_id,label_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind = 'label' AND label_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_id,question_response_id,decision_id,presentation_element_id,question_option_id,binding_id,dataset_value_id,revision_id,source_record_id,field_definition_id) = 0) OR
               (kind = 'project_input_binding' AND binding_id IS NOT NULL AND field_definition_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_id,question_response_id,decision_id,presentation_element_id,question_option_id,label_id,dataset_value_id,revision_id,source_record_id) = 0) OR
               (kind = 'dataset_value' AND binding_id IS NOT NULL AND dataset_value_id IS NOT NULL AND revision_id IS NOT NULL AND source_record_id IS NOT NULL AND field_definition_id IS NOT NULL AND num_nonnulls(task_id,attempt_id,question_id,question_response_id,decision_id,presentation_element_id,question_option_id,label_id) = 0)

             """
           )
  end
end
