defmodule QuickTrain.Repo.Migrations.AddVersionedForms do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:form_bound_values, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :element_id, :uuid, null: false
    end

    create unique_index(:form_bound_values, [:element_id],
             name: "form_bound_values_element_index"
           )

    alter table(:form_bound_values) do
      add :requirement_id, :uuid, null: false
      add :version_id, :uuid, null: false
    end

    create index(:form_bound_values, [:id, :version_id], unique: true)

    create table(:form_text_constraints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :minimum, :bigint
      add :maximum, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_text_constraints, [:question_id],
             name: "form_text_constraints_question_index"
           )

    alter table(:form_text_constraints) do
      add :version_id, :uuid, null: false
    end

    create index(:form_text_constraints, [:id, :version_id], unique: true)

    create table(:form_instructions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :element_id, :uuid, null: false
    end

    create unique_index(:form_instructions, [:element_id],
             name: "form_instructions_element_index"
           )

    alter table(:form_instructions) do
      add :version_id, :uuid, null: false
    end

    create index(:form_instructions, [:id, :version_id], unique: true)

    create table(:form_question_options, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :label, :text, null: false
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_question_options, [:question_id, :key],
             name: "form_question_options_parent_key_index"
           )

    alter table(:form_question_options) do
      add :version_id, :uuid, null: false
    end

    create index(:form_question_options, [:id, :version_id], unique: true)

    create table(:forms, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "forms_organization_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:forms, [:organization_id, :key], name: "forms_parent_key_index")

    create table(:form_integer_constraints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :minimum, :bigint
      add :maximum, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_integer_constraints, [:question_id],
             name: "form_integer_constraints_question_index"
           )

    alter table(:form_integer_constraints) do
      add :version_id, :uuid, null: false
    end

    create index(:form_integer_constraints, [:id, :version_id], unique: true)

    create table(:form_question_placements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :element_id, :uuid, null: false
    end

    create unique_index(:form_question_placements, [:element_id],
             name: "form_question_placements_element_index"
           )

    alter table(:form_question_placements) do
      add :question_id, :uuid, null: false
      add :version_id, :uuid, null: false
    end

    create index(:form_question_placements, [:id, :version_id], unique: true)

    create table(:form_versions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:form_bound_values) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_bound_values_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_text_constraints) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_text_constraints_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_instructions) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_instructions_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_question_options) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_question_options_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_integer_constraints) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_integer_constraints_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_question_placements) do
      modify :version_id,
             references(:form_versions,
               column: :id,
               name: "form_question_placements_version_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_versions) do
      add :version, :bigint, null: false
      add :state, :text, null: false, default: "draft"
      add :title, :text
      add :description, :text
      add :published_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :form_id,
          references(:forms,
            column: :id,
            name: "form_versions_form_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_versions, [:form_id, :version],
             name: "form_versions_form_version_index"
           )

    create constraint(:form_versions, :form_versions_check_0,
             check: """
               version BETWEEN 1 AND 2147483647
             """
           )

    create constraint(:form_versions, :form_versions_check_1,
             check: """
               state IN ('draft', 'published')
             """
           )

    create constraint(:form_versions, :form_versions_check_2,
             check: """
               (state = 'draft' AND published_at IS NULL) OR (state = 'published' AND published_at IS NOT NULL)
             """
           )

    create table(:form_sections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :element_id, :uuid, null: false
    end

    create unique_index(:form_sections, [:element_id], name: "form_sections_element_index")

    alter table(:form_sections) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_sections_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:form_sections, [:id, :version_id], unique: true)

    create table(:form_label_sets, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_label_sets_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_label_sets, [:version_id, :key],
             name: "form_label_sets_parent_key_index"
           )

    create index(:form_label_sets, [:id, :version_id], unique: true)

    create table(:form_input_slot_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :minimum, :bigint, null: false
      add :maximum, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_input_slot_definitions_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_input_slot_definitions, [:version_id, :key],
             name: "form_input_slot_definitions_parent_key_index"
           )

    create constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_0,
             check: """
               minimum BETWEEN 1 AND 100
             """
           )

    create constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_1,
             check: """
               maximum BETWEEN 1 AND 100
             """
           )

    create constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_2,
             check: """
               minimum <= maximum
             """
           )

    create index(:form_input_slot_definitions, [:id, :version_id], unique: true)

    create table(:form_headings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :text, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :element_id, :uuid, null: false
    end

    create unique_index(:form_headings, [:element_id], name: "form_headings_element_index")

    alter table(:form_headings) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_headings_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:form_headings, [:id, :version_id], unique: true)

    create table(:form_input_field_requirements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :value_family, :text, null: false
      add :cardinality, :text, null: false, default: "single"
      add :required, :boolean, null: false
      add :intended_use, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :input_slot_id, :uuid, null: false
    end

    create unique_index(:form_input_field_requirements, [:input_slot_id, :key],
             name: "form_input_field_requirements_parent_key_index"
           )

    alter table(:form_input_field_requirements) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_input_field_requirements_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      modify :input_slot_id,
             references(:form_input_slot_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_input_field_requirements_input_slot_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_input_field_requirements, :form_input_field_requirements_check_0,
             check: """
               value_family IN ('text', 'integer', 'decimal', 'boolean', 'utc_datetime', 'asset')
             """
           )

    create constraint(:form_input_field_requirements, :form_input_field_requirements_check_1,
             check: """
               cardinality IN ('single')
             """
           )

    create constraint(:form_input_field_requirements, :form_input_field_requirements_check_2,
             check: """
               intended_use IN ('download', 'image')
             """
           )

    create constraint(:form_input_field_requirements, :form_input_field_requirements_check_3,
             check: """
               (value_family = 'asset' AND intended_use IS NOT NULL) OR (value_family <> 'asset' AND intended_use IS NULL)
             """
           )

    create index(:form_input_field_requirements, [:id, :version_id], unique: true)

    alter table(:form_bound_values) do
      modify :requirement_id,
             references(:form_input_field_requirements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_bound_values_requirement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create table(:form_input_sources, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_input_sources, [:question_id],
             name: "form_input_sources_question_index"
           )

    alter table(:form_input_sources) do
      add :input_slot_id, :uuid, null: false
      add :source_requirement_id, :uuid

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_input_sources_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    alter table(:form_input_sources) do
      modify :input_slot_id,
             references(:form_input_slot_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_input_sources_input_slot_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :source_requirement_id,
             references(:form_input_field_requirements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_input_sources_source_requirement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create index(:form_input_sources, [:id, :version_id], unique: true)

    create table(:form_decimal_constraints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :minimum, :decimal
      add :maximum, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_decimal_constraints, [:question_id],
             name: "form_decimal_constraints_question_index"
           )

    alter table(:form_decimal_constraints) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_decimal_constraints_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create index(:form_decimal_constraints, [:id, :version_id], unique: true)

    create table(:form_presentation_elements, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_presentation_elements_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create constraint(:form_presentation_elements, :form_presentation_elements_check_0,
             check: """
               kind IN ('instruction', 'heading', 'section', 'bound_value', 'question')
             """
           )

    create constraint(:form_presentation_elements, :form_presentation_elements_check_1,
             check: """
               position BETWEEN 0 AND 2147483647
             """
           )

    create index(:form_presentation_elements, [:id, :version_id], unique: true)

    alter table(:form_bound_values) do
      modify :element_id,
             references(:form_presentation_elements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_bound_values_element_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_instructions) do
      modify :element_id,
             references(:form_presentation_elements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_instructions_element_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_question_placements) do
      modify :element_id,
             references(:form_presentation_elements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_question_placements_element_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_sections) do
      modify :element_id,
             references(:form_presentation_elements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_sections_element_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_headings) do
      modify :element_id,
             references(:form_presentation_elements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_headings_element_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create table(:form_question_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :prompt, :text, null: false
      add :family, :text, null: false
      add :renderer, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_question_definitions_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    create unique_index(:form_question_definitions, [:version_id, :key],
             name: "form_question_definitions_parent_key_index"
           )

    create constraint(:form_question_definitions, :form_question_definitions_check_0,
             check: """
               family IN ('text', 'integer', 'decimal', 'boolean', 'static_single_choice', 'static_multiple_choice', 'task_input_single_choice', 'task_input_multiple_choice', 'task_input_ranking', 'bounding_boxes', 'polygon_regions', 'raster_masks', 'text_spans')
             """
           )

    create constraint(:form_question_definitions, :form_question_definitions_check_1,
             check: """
               renderer IN ('text_input', 'text_area', 'integer_input', 'stars', 'likert', 'decimal_input', 'checkbox', 'toggle', 'radio', 'dropdown', 'checkbox_group', 'pairwise', 'image_choice', 'ranking', 'bounding_boxes', 'polygon_regions', 'raster_masks', 'text_spans')
             """
           )

    create index(:form_question_definitions, [:id, :version_id], unique: true)

    alter table(:form_text_constraints) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_text_constraints_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_text_constraints, :form_text_constraints_check_0,
             check: """
               minimum BETWEEN 0 AND 2147483647
             """
           )

    create constraint(:form_text_constraints, :form_text_constraints_check_1,
             check: """
               maximum BETWEEN 0 AND 2147483647
             """
           )

    create constraint(:form_text_constraints, :form_text_constraints_check_2,
             check: """
               minimum <= maximum
             """
           )

    alter table(:form_question_options) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_question_options_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_question_options, :form_question_options_check_0,
             check: """
               position BETWEEN 0 AND 2147483647
             """
           )

    alter table(:form_integer_constraints) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_integer_constraints_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_integer_constraints, :form_integer_constraints_check_0,
             check: """
               minimum BETWEEN -2147483648 AND 2147483647
             """
           )

    create constraint(:form_integer_constraints, :form_integer_constraints_check_1,
             check: """
               maximum BETWEEN -2147483648 AND 2147483647
             """
           )

    create constraint(:form_integer_constraints, :form_integer_constraints_check_2,
             check: """
               minimum <= maximum
             """
           )

    alter table(:form_question_placements) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_question_placements_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_input_sources) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_input_sources_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    alter table(:form_decimal_constraints) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_decimal_constraints_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_decimal_constraints, :form_decimal_constraints_check_0,
             check: """
               minimum <= maximum
             """
           )

    create table(:form_annotation_constraints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :minimum, :bigint, null: false
      add :maximum, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_annotation_constraints, [:question_id],
             name: "form_annotation_constraints_question_index"
           )

    alter table(:form_annotation_constraints) do
      add :source_requirement_id, :uuid, null: false
      add :label_set_id, :uuid, null: false

      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_annotation_constraints_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false
    end

    alter table(:form_annotation_constraints) do
      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_annotation_constraints_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :source_requirement_id,
             references(:form_input_field_requirements,
               column: :id,
               with: [version_id: :version_id],
               name: "form_annotation_constraints_source_requirement_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )

      modify :label_set_id,
             references(:form_label_sets,
               column: :id,
               with: [version_id: :version_id],
               name: "form_annotation_constraints_label_set_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_annotation_constraints, :form_annotation_constraints_check_0,
             check: """
               minimum BETWEEN 0 AND 2147483647
             """
           )

    create constraint(:form_annotation_constraints, :form_annotation_constraints_check_1,
             check: """
               maximum BETWEEN 0 AND 2147483647
             """
           )

    create constraint(:form_annotation_constraints, :form_annotation_constraints_check_2,
             check: """
               minimum <= maximum
             """
           )

    create index(:form_annotation_constraints, [:id, :version_id], unique: true)

    create table(:form_selection_constraints, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :minimum, :bigint, null: false
      add :maximum, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :question_id, :uuid, null: false
    end

    create unique_index(:form_selection_constraints, [:question_id],
             name: "form_selection_constraints_question_index"
           )

    alter table(:form_selection_constraints) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_selection_constraints_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      modify :question_id,
             references(:form_question_definitions,
               column: :id,
               with: [version_id: :version_id],
               name: "form_selection_constraints_question_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_selection_constraints, :form_selection_constraints_check_0,
             check: """
               minimum BETWEEN 1 AND 200
             """
           )

    create constraint(:form_selection_constraints, :form_selection_constraints_check_1,
             check: """
               maximum BETWEEN 1 AND 200
             """
           )

    create constraint(:form_selection_constraints, :form_selection_constraints_check_2,
             check: """
               minimum <= maximum
             """
           )

    create index(:form_selection_constraints, [:id, :version_id], unique: true)

    create table(:form_labels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false
      add :text, :text, null: false
      add :position, :bigint, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :label_set_id, :uuid, null: false
    end

    create unique_index(:form_labels, [:label_set_id, :key], name: "form_labels_parent_key_index")

    alter table(:form_labels) do
      add :version_id,
          references(:form_versions,
            column: :id,
            name: "form_labels_version_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :restrict
          ),
          null: false

      modify :label_set_id,
             references(:form_label_sets,
               column: :id,
               with: [version_id: :version_id],
               name: "form_labels_label_set_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :restrict
             )
    end

    create constraint(:form_labels, :form_labels_check_0,
             check: """
               position BETWEEN 0 AND 2147483647
             """
           )

    create index(:form_labels, [:id, :version_id], unique: true)

    execute("""
    DO $forms_migration$ BEGIN
    EXECUTE $forms_ddl$CREATE FUNCTION quick_train_form_owner_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_TABLE_NAME = 'forms' THEN
        IF TG_OP = 'UPDATE' AND (NEW.id, NEW.organization_id, NEW.key) IS DISTINCT FROM (OLD.id, OLD.organization_id, OLD.key) THEN
          RAISE EXCEPTION 'immutable form identity' USING ERRCODE = '23514';
        END IF;
      ELSE
        IF TG_OP = 'INSERT' THEN
          IF NEW.state <> 'draft' OR NEW.published_at IS NOT NULL THEN
            RAISE EXCEPTION 'new form versions must be drafts' USING ERRCODE = '23514';
          END IF;
        ELSE
          IF OLD.state = 'published' THEN
            RAISE EXCEPTION 'published form version is immutable' USING ERRCODE = '23514';
          END IF;
          IF TG_OP = 'UPDATE' AND (NEW.id, NEW.form_id, NEW.version) IS DISTINCT FROM (OLD.id, OLD.form_id, OLD.version) THEN
            RAISE EXCEPTION 'immutable form version identity' USING ERRCODE = '23514';
          END IF;
        END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$;
    $forms_ddl$;
    EXECUTE $forms_ddl$CREATE FUNCTION quick_train_form_child_guard() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE owner_id uuid; owner_state text;
    BEGIN
      IF TG_OP = 'INSERT' THEN owner_id := NEW.version_id; ELSE owner_id := OLD.version_id; END IF;
      SELECT state INTO owner_state FROM form_versions WHERE id = owner_id FOR UPDATE;
      IF owner_state IS DISTINCT FROM 'draft' THEN
        RAISE EXCEPTION 'form version must be a draft' USING ERRCODE = '23514';
      END IF;
      IF TG_OP = 'UPDATE' THEN
        IF (OLD.id, OLD.version_id) IS DISTINCT FROM (NEW.id, NEW.version_id) THEN
          RAISE EXCEPTION 'immutable definition ownership' USING ERRCODE = '23514';
        END IF;
        IF TG_TABLE_NAME IN ('form_input_slot_definitions','form_input_field_requirements','form_question_definitions','form_question_options','form_label_sets','form_labels') THEN
          IF OLD.key IS DISTINCT FROM NEW.key THEN RAISE EXCEPTION 'immutable definition key' USING ERRCODE = '23514'; END IF;
        END IF;
        IF TG_TABLE_NAME = 'form_input_field_requirements' THEN
          IF OLD.input_slot_id IS DISTINCT FROM NEW.input_slot_id THEN RAISE EXCEPTION 'immutable input slot ownership' USING ERRCODE = '23514'; END IF;
        ELSIF TG_TABLE_NAME = 'form_labels' THEN
          IF OLD.label_set_id IS DISTINCT FROM NEW.label_set_id THEN RAISE EXCEPTION 'immutable label ownership' USING ERRCODE = '23514'; END IF;
        ELSIF TG_TABLE_NAME IN ('form_text_constraints','form_integer_constraints','form_decimal_constraints','form_selection_constraints','form_annotation_constraints','form_input_sources','form_question_options') THEN
          IF OLD.question_id IS DISTINCT FROM NEW.question_id THEN RAISE EXCEPTION 'immutable question ownership' USING ERRCODE = '23514'; END IF;
        ELSIF TG_TABLE_NAME IN ('form_instructions','form_headings','form_sections','form_bound_values','form_question_placements') THEN
          IF OLD.element_id IS DISTINCT FROM NEW.element_id THEN RAISE EXCEPTION 'immutable element ownership' USING ERRCODE = '23514'; END IF;
        ELSIF TG_TABLE_NAME = 'form_presentation_elements' THEN
          IF OLD.kind IS DISTINCT FROM NEW.kind THEN RAISE EXCEPTION 'immutable element kind' USING ERRCODE = '23514'; END IF;
        END IF;
      END IF;
      IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
      RETURN NEW;
    END; $$;
    $forms_ddl$;
    EXECUTE $forms_ddl$CREATE FUNCTION quick_train_check_form_presentation(element_uuid uuid) RETURNS void LANGUAGE plpgsql AS $$
    DECLARE element_kind text; matching bigint; total bigint;
    BEGIN
      SELECT kind INTO element_kind FROM form_presentation_elements WHERE id = element_uuid;
      IF NOT FOUND THEN RETURN; END IF;
      SELECT count(*), count(*) FILTER (WHERE kind = element_kind) INTO total, matching FROM (
        SELECT 'instruction' AS kind FROM form_instructions WHERE element_id = element_uuid
        UNION ALL SELECT 'heading' FROM form_headings WHERE element_id = element_uuid
        UNION ALL SELECT 'section' FROM form_sections WHERE element_id = element_uuid
        UNION ALL SELECT 'bound_value' FROM form_bound_values WHERE element_id = element_uuid
        UNION ALL SELECT 'question' FROM form_question_placements WHERE element_id = element_uuid
      ) children;
      IF total <> 1 OR matching <> 1 THEN
        RAISE EXCEPTION 'presentation requires one matching subtype' USING ERRCODE = '23514';
      END IF;
    END; $$;
    $forms_ddl$;
    EXECUTE $forms_ddl$CREATE FUNCTION quick_train_check_form_question(question_uuid uuid) RETURNS void LANGUAGE plpgsql AS $$
    DECLARE answer_family text; invalid boolean;
    BEGIN
      SELECT family INTO answer_family FROM form_question_definitions WHERE id = question_uuid;
      IF NOT FOUND THEN RETURN; END IF;
      SELECT EXISTS (
        SELECT 1 FROM form_text_constraints WHERE question_id = question_uuid AND answer_family <> 'text'
        UNION ALL SELECT 1 FROM form_integer_constraints WHERE question_id = question_uuid AND answer_family <> 'integer'
        UNION ALL SELECT 1 FROM form_decimal_constraints WHERE question_id = question_uuid AND answer_family <> 'decimal'
        UNION ALL SELECT 1 FROM form_selection_constraints WHERE question_id = question_uuid AND answer_family NOT IN ('static_single_choice','static_multiple_choice','task_input_single_choice','task_input_multiple_choice')
        UNION ALL SELECT 1 FROM form_annotation_constraints WHERE question_id = question_uuid AND answer_family NOT IN ('bounding_boxes','polygon_regions','raster_masks','text_spans')
        UNION ALL SELECT 1 FROM form_input_sources WHERE question_id = question_uuid AND answer_family NOT IN ('task_input_single_choice','task_input_multiple_choice','task_input_ranking')
        UNION ALL SELECT 1 FROM form_question_options WHERE question_id = question_uuid AND answer_family NOT IN ('static_single_choice','static_multiple_choice')
      ) INTO invalid;
      IF invalid THEN RAISE EXCEPTION 'incompatible question subtype' USING ERRCODE = '23514'; END IF;
    END; $$;
    $forms_ddl$;
    EXECUTE $forms_ddl$CREATE FUNCTION quick_train_form_typed_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
    DECLARE owner_uuid uuid;
    BEGIN
      IF TG_ARGV[0] = 'presentation' THEN
        IF TG_TABLE_NAME = 'form_presentation_elements' THEN
          IF TG_OP = 'DELETE' THEN owner_uuid := OLD.id; ELSE owner_uuid := NEW.id; END IF;
        ELSE
          IF TG_OP = 'DELETE' THEN owner_uuid := OLD.element_id; ELSE owner_uuid := NEW.element_id; END IF;
        END IF;
        PERFORM quick_train_check_form_presentation(owner_uuid);
      ELSE
        IF TG_TABLE_NAME = 'form_question_definitions' THEN
          IF TG_OP = 'DELETE' THEN owner_uuid := OLD.id; ELSE owner_uuid := NEW.id; END IF;
        ELSE
          IF TG_OP = 'DELETE' THEN owner_uuid := OLD.question_id; ELSE owner_uuid := NEW.question_id; END IF;
        END IF;
        PERFORM quick_train_check_form_question(owner_uuid);
      END IF;
      RETURN NULL;
    END; $$;
    $forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER forms_owner_guard BEFORE UPDATE OR DELETE ON forms FOR EACH ROW EXECUTE FUNCTION quick_train_form_owner_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_versions_owner_guard BEFORE INSERT OR UPDATE OR DELETE ON form_versions FOR EACH ROW EXECUTE FUNCTION quick_train_form_owner_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_input_slot_definitions_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_input_slot_definitions FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_input_field_requirements_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_input_field_requirements FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_question_definitions_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_question_definitions FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_text_constraints_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_text_constraints FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_integer_constraints_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_integer_constraints FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_decimal_constraints_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_decimal_constraints FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_selection_constraints_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_selection_constraints FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_annotation_constraints_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_annotation_constraints FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_input_sources_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_input_sources FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_question_options_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_question_options FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_label_sets_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_label_sets FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_labels_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_labels FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_presentation_elements_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_presentation_elements FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_instructions_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_instructions FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_headings_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_headings FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_sections_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_sections FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_bound_values_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_bound_values FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE TRIGGER form_question_placements_draft_guard BEFORE INSERT OR UPDATE OR DELETE ON form_question_placements FOR EACH ROW EXECUTE FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_presentation_elements_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_presentation_elements DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_instructions_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_instructions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_headings_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_headings DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_sections_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_sections DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_bound_values_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_bound_values DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_question_placements_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_question_placements DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('presentation');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_question_definitions_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_question_definitions DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_text_constraints_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_text_constraints DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_integer_constraints_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_integer_constraints DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_decimal_constraints_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_decimal_constraints DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_selection_constraints_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_selection_constraints DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_annotation_constraints_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_annotation_constraints DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_input_sources_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_input_sources DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$CREATE CONSTRAINT TRIGGER form_question_options_typed_guard AFTER INSERT OR UPDATE OR DELETE ON form_question_options DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION quick_train_form_typed_trigger('question');$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_presentation_elements ADD CONSTRAINT form_presentation_elements_position_unique UNIQUE (version_id, position) DEFERRABLE INITIALLY DEFERRED;$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_question_options ADD CONSTRAINT form_question_options_position_unique UNIQUE (question_id, position) DEFERRABLE INITIALLY DEFERRED;$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_labels ADD CONSTRAINT form_labels_position_unique UNIQUE (label_set_id, position) DEFERRABLE INITIALLY DEFERRED;$forms_ddl$;
    END $forms_migration$;
    """)
  end

  def down do
    execute("""
    DO $forms_migration$ BEGIN
    EXECUTE $forms_ddl$DROP TRIGGER forms_owner_guard ON forms;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_versions_owner_guard ON form_versions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_input_slot_definitions_draft_guard ON form_input_slot_definitions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_input_field_requirements_draft_guard ON form_input_field_requirements;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_definitions_draft_guard ON form_question_definitions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_text_constraints_draft_guard ON form_text_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_integer_constraints_draft_guard ON form_integer_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_decimal_constraints_draft_guard ON form_decimal_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_selection_constraints_draft_guard ON form_selection_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_annotation_constraints_draft_guard ON form_annotation_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_input_sources_draft_guard ON form_input_sources;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_options_draft_guard ON form_question_options;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_label_sets_draft_guard ON form_label_sets;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_labels_draft_guard ON form_labels;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_presentation_elements_draft_guard ON form_presentation_elements;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_instructions_draft_guard ON form_instructions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_headings_draft_guard ON form_headings;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_sections_draft_guard ON form_sections;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_bound_values_draft_guard ON form_bound_values;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_placements_draft_guard ON form_question_placements;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_presentation_elements_typed_guard ON form_presentation_elements;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_instructions_typed_guard ON form_instructions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_headings_typed_guard ON form_headings;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_sections_typed_guard ON form_sections;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_bound_values_typed_guard ON form_bound_values;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_placements_typed_guard ON form_question_placements;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_definitions_typed_guard ON form_question_definitions;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_text_constraints_typed_guard ON form_text_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_integer_constraints_typed_guard ON form_integer_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_decimal_constraints_typed_guard ON form_decimal_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_selection_constraints_typed_guard ON form_selection_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_annotation_constraints_typed_guard ON form_annotation_constraints;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_input_sources_typed_guard ON form_input_sources;$forms_ddl$;
    EXECUTE $forms_ddl$DROP TRIGGER form_question_options_typed_guard ON form_question_options;$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_presentation_elements DROP CONSTRAINT form_presentation_elements_position_unique;$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_question_options DROP CONSTRAINT form_question_options_position_unique;$forms_ddl$;
    EXECUTE $forms_ddl$ALTER TABLE form_labels DROP CONSTRAINT form_labels_position_unique;$forms_ddl$;
    EXECUTE $forms_ddl$DROP FUNCTION quick_train_form_typed_trigger();$forms_ddl$;
    EXECUTE $forms_ddl$DROP FUNCTION quick_train_check_form_question(uuid);$forms_ddl$;
    EXECUTE $forms_ddl$DROP FUNCTION quick_train_check_form_presentation(uuid);$forms_ddl$;
    EXECUTE $forms_ddl$DROP FUNCTION quick_train_form_child_guard();$forms_ddl$;
    EXECUTE $forms_ddl$DROP FUNCTION quick_train_form_owner_guard();$forms_ddl$;
    END $forms_migration$;
    """)

    drop_if_exists index(:form_labels, [:id, :version_id])

    drop_if_exists constraint(:form_labels, :form_labels_check_0)

    drop constraint(:form_labels, "form_labels_version_id_fkey")

    drop constraint(:form_labels, "form_labels_label_set_id_fkey")

    alter table(:form_labels) do
      modify :label_set_id, :uuid
      remove :version_id
    end

    drop_if_exists unique_index(:form_labels, [:label_set_id, :key],
                     name: "form_labels_parent_key_index"
                   )

    drop table(:form_labels)

    drop_if_exists index(:form_selection_constraints, [:id, :version_id])

    drop_if_exists constraint(:form_selection_constraints, :form_selection_constraints_check_2)

    drop_if_exists constraint(:form_selection_constraints, :form_selection_constraints_check_1)

    drop_if_exists constraint(:form_selection_constraints, :form_selection_constraints_check_0)

    drop constraint(:form_selection_constraints, "form_selection_constraints_version_id_fkey")

    drop constraint(:form_selection_constraints, "form_selection_constraints_question_id_fkey")

    alter table(:form_selection_constraints) do
      modify :question_id, :uuid
      remove :version_id
    end

    drop_if_exists unique_index(:form_selection_constraints, [:question_id],
                     name: "form_selection_constraints_question_index"
                   )

    drop table(:form_selection_constraints)

    drop_if_exists index(:form_annotation_constraints, [:id, :version_id])

    drop_if_exists constraint(:form_annotation_constraints, :form_annotation_constraints_check_2)

    drop_if_exists constraint(:form_annotation_constraints, :form_annotation_constraints_check_1)

    drop_if_exists constraint(:form_annotation_constraints, :form_annotation_constraints_check_0)

    drop constraint(:form_annotation_constraints, "form_annotation_constraints_version_id_fkey")

    drop constraint(:form_annotation_constraints, "form_annotation_constraints_label_set_id_fkey")

    drop constraint(
           :form_annotation_constraints,
           "form_annotation_constraints_source_requirement_id_fkey"
         )

    drop constraint(:form_annotation_constraints, "form_annotation_constraints_question_id_fkey")

    alter table(:form_annotation_constraints) do
      modify :question_id, :uuid
      remove :version_id
      remove :label_set_id
      remove :source_requirement_id
    end

    drop_if_exists unique_index(:form_annotation_constraints, [:question_id],
                     name: "form_annotation_constraints_question_index"
                   )

    drop table(:form_annotation_constraints)

    drop_if_exists constraint(:form_decimal_constraints, :form_decimal_constraints_check_0)

    drop constraint(:form_decimal_constraints, "form_decimal_constraints_version_id_fkey")

    drop constraint(:form_decimal_constraints, "form_decimal_constraints_question_id_fkey")

    alter table(:form_decimal_constraints) do
      modify :question_id, :uuid
    end

    drop constraint(:form_input_sources, "form_input_sources_version_id_fkey")

    drop constraint(:form_input_sources, "form_input_sources_source_requirement_id_fkey")

    drop constraint(:form_input_sources, "form_input_sources_input_slot_id_fkey")

    drop constraint(:form_input_sources, "form_input_sources_question_id_fkey")

    alter table(:form_input_sources) do
      modify :question_id, :uuid
    end

    drop constraint(:form_question_placements, "form_question_placements_version_id_fkey")

    drop constraint(:form_question_placements, "form_question_placements_question_id_fkey")

    drop constraint(:form_question_placements, "form_question_placements_element_id_fkey")

    alter table(:form_question_placements) do
      modify :question_id, :uuid
    end

    drop_if_exists constraint(:form_integer_constraints, :form_integer_constraints_check_2)

    drop_if_exists constraint(:form_integer_constraints, :form_integer_constraints_check_1)

    drop_if_exists constraint(:form_integer_constraints, :form_integer_constraints_check_0)

    drop constraint(:form_integer_constraints, "form_integer_constraints_version_id_fkey")

    drop constraint(:form_integer_constraints, "form_integer_constraints_question_id_fkey")

    alter table(:form_integer_constraints) do
      modify :question_id, :uuid
    end

    drop_if_exists constraint(:form_question_options, :form_question_options_check_0)

    drop constraint(:form_question_options, "form_question_options_version_id_fkey")

    drop constraint(:form_question_options, "form_question_options_question_id_fkey")

    alter table(:form_question_options) do
      modify :question_id, :uuid
    end

    drop_if_exists constraint(:form_text_constraints, :form_text_constraints_check_2)

    drop_if_exists constraint(:form_text_constraints, :form_text_constraints_check_1)

    drop_if_exists constraint(:form_text_constraints, :form_text_constraints_check_0)

    drop constraint(:form_text_constraints, "form_text_constraints_version_id_fkey")

    drop constraint(:form_text_constraints, "form_text_constraints_question_id_fkey")

    alter table(:form_text_constraints) do
      modify :question_id, :uuid
    end

    drop_if_exists index(:form_question_definitions, [:id, :version_id])

    drop_if_exists constraint(:form_question_definitions, :form_question_definitions_check_1)

    drop_if_exists constraint(:form_question_definitions, :form_question_definitions_check_0)

    drop constraint(:form_question_definitions, "form_question_definitions_version_id_fkey")

    drop_if_exists unique_index(:form_question_definitions, [:version_id, :key],
                     name: "form_question_definitions_parent_key_index"
                   )

    drop table(:form_question_definitions)

    drop constraint(:form_headings, "form_headings_version_id_fkey")

    drop constraint(:form_headings, "form_headings_element_id_fkey")

    alter table(:form_headings) do
      modify :element_id, :uuid
    end

    drop constraint(:form_sections, "form_sections_version_id_fkey")

    drop constraint(:form_sections, "form_sections_element_id_fkey")

    alter table(:form_sections) do
      modify :element_id, :uuid
    end

    alter table(:form_question_placements) do
      modify :element_id, :uuid
    end

    drop constraint(:form_instructions, "form_instructions_version_id_fkey")

    drop constraint(:form_instructions, "form_instructions_element_id_fkey")

    alter table(:form_instructions) do
      modify :element_id, :uuid
    end

    drop constraint(:form_bound_values, "form_bound_values_version_id_fkey")

    drop constraint(:form_bound_values, "form_bound_values_requirement_id_fkey")

    drop constraint(:form_bound_values, "form_bound_values_element_id_fkey")

    alter table(:form_bound_values) do
      modify :element_id, :uuid
    end

    drop_if_exists index(:form_presentation_elements, [:id, :version_id])

    drop_if_exists constraint(:form_presentation_elements, :form_presentation_elements_check_1)

    drop_if_exists constraint(:form_presentation_elements, :form_presentation_elements_check_0)

    drop constraint(:form_presentation_elements, "form_presentation_elements_version_id_fkey")

    drop table(:form_presentation_elements)

    drop_if_exists index(:form_decimal_constraints, [:id, :version_id])

    alter table(:form_decimal_constraints) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_decimal_constraints, [:question_id],
                     name: "form_decimal_constraints_question_index"
                   )

    drop table(:form_decimal_constraints)

    drop_if_exists index(:form_input_sources, [:id, :version_id])

    alter table(:form_input_sources) do
      remove :version_id
      remove :source_requirement_id
      remove :input_slot_id
    end

    drop_if_exists unique_index(:form_input_sources, [:question_id],
                     name: "form_input_sources_question_index"
                   )

    drop table(:form_input_sources)

    alter table(:form_bound_values) do
      modify :requirement_id, :uuid
    end

    drop_if_exists index(:form_input_field_requirements, [:id, :version_id])

    drop_if_exists constraint(
                     :form_input_field_requirements,
                     :form_input_field_requirements_check_3
                   )

    drop_if_exists constraint(
                     :form_input_field_requirements,
                     :form_input_field_requirements_check_2
                   )

    drop_if_exists constraint(
                     :form_input_field_requirements,
                     :form_input_field_requirements_check_1
                   )

    drop_if_exists constraint(
                     :form_input_field_requirements,
                     :form_input_field_requirements_check_0
                   )

    drop constraint(
           :form_input_field_requirements,
           "form_input_field_requirements_version_id_fkey"
         )

    drop constraint(
           :form_input_field_requirements,
           "form_input_field_requirements_input_slot_id_fkey"
         )

    alter table(:form_input_field_requirements) do
      modify :input_slot_id, :uuid
      remove :version_id
    end

    drop_if_exists unique_index(:form_input_field_requirements, [:input_slot_id, :key],
                     name: "form_input_field_requirements_parent_key_index"
                   )

    drop table(:form_input_field_requirements)

    drop_if_exists index(:form_headings, [:id, :version_id])

    alter table(:form_headings) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_headings, [:element_id],
                     name: "form_headings_element_index"
                   )

    drop table(:form_headings)

    drop_if_exists index(:form_input_slot_definitions, [:id, :version_id])

    drop_if_exists constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_2)

    drop_if_exists constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_1)

    drop_if_exists constraint(:form_input_slot_definitions, :form_input_slot_definitions_check_0)

    drop constraint(:form_input_slot_definitions, "form_input_slot_definitions_version_id_fkey")

    drop_if_exists unique_index(:form_input_slot_definitions, [:version_id, :key],
                     name: "form_input_slot_definitions_parent_key_index"
                   )

    drop table(:form_input_slot_definitions)

    drop_if_exists index(:form_label_sets, [:id, :version_id])

    drop constraint(:form_label_sets, "form_label_sets_version_id_fkey")

    drop_if_exists unique_index(:form_label_sets, [:version_id, :key],
                     name: "form_label_sets_parent_key_index"
                   )

    drop table(:form_label_sets)

    drop_if_exists index(:form_sections, [:id, :version_id])

    alter table(:form_sections) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_sections, [:element_id],
                     name: "form_sections_element_index"
                   )

    drop table(:form_sections)

    drop_if_exists constraint(:form_versions, :form_versions_check_2)

    drop_if_exists constraint(:form_versions, :form_versions_check_1)

    drop_if_exists constraint(:form_versions, :form_versions_check_0)

    drop constraint(:form_versions, "form_versions_form_id_fkey")

    drop_if_exists unique_index(:form_versions, [:form_id, :version],
                     name: "form_versions_form_version_index"
                   )

    alter table(:form_versions) do
      remove :form_id
      remove :updated_at
      remove :inserted_at
      remove :published_at
      remove :description
      remove :title
      remove :state
      remove :version
    end

    alter table(:form_question_placements) do
      modify :version_id, :uuid
    end

    alter table(:form_integer_constraints) do
      modify :version_id, :uuid
    end

    alter table(:form_question_options) do
      modify :version_id, :uuid
    end

    alter table(:form_instructions) do
      modify :version_id, :uuid
    end

    alter table(:form_text_constraints) do
      modify :version_id, :uuid
    end

    alter table(:form_bound_values) do
      modify :version_id, :uuid
    end

    drop table(:form_versions)

    drop_if_exists index(:form_question_placements, [:id, :version_id])

    alter table(:form_question_placements) do
      remove :version_id
      remove :question_id
    end

    drop_if_exists unique_index(:form_question_placements, [:element_id],
                     name: "form_question_placements_element_index"
                   )

    drop table(:form_question_placements)

    drop_if_exists index(:form_integer_constraints, [:id, :version_id])

    alter table(:form_integer_constraints) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_integer_constraints, [:question_id],
                     name: "form_integer_constraints_question_index"
                   )

    drop table(:form_integer_constraints)

    drop constraint(:forms, "forms_organization_id_fkey")

    drop_if_exists unique_index(:forms, [:organization_id, :key], name: "forms_parent_key_index")

    drop table(:forms)

    drop_if_exists index(:form_question_options, [:id, :version_id])

    alter table(:form_question_options) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_question_options, [:question_id, :key],
                     name: "form_question_options_parent_key_index"
                   )

    drop table(:form_question_options)

    drop_if_exists index(:form_instructions, [:id, :version_id])

    alter table(:form_instructions) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_instructions, [:element_id],
                     name: "form_instructions_element_index"
                   )

    drop table(:form_instructions)

    drop_if_exists index(:form_text_constraints, [:id, :version_id])

    alter table(:form_text_constraints) do
      remove :version_id
    end

    drop_if_exists unique_index(:form_text_constraints, [:question_id],
                     name: "form_text_constraints_question_index"
                   )

    drop table(:form_text_constraints)

    drop_if_exists index(:form_bound_values, [:id, :version_id])

    alter table(:form_bound_values) do
      remove :version_id
      remove :requirement_id
    end

    drop_if_exists unique_index(:form_bound_values, [:element_id],
                     name: "form_bound_values_element_index"
                   )

    drop table(:form_bound_values)
  end
end
