defmodule QuickTrain.Repo.Migrations.ReportFormPositionConflicts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    execute("""
    ALTER TABLE form_question_options DROP CONSTRAINT form_question_options_position_unique;
    """)

    execute("""
    ALTER TABLE form_presentation_elements DROP CONSTRAINT form_presentation_elements_position_unique;
    """)

    execute("""
    ALTER TABLE form_labels DROP CONSTRAINT form_labels_position_unique;
    """)

    execute("""
    ALTER TABLE form_question_options ADD CONSTRAINT form_question_options_position_unique UNIQUE (question_id, position) DEFERRABLE INITIALLY IMMEDIATE;
    """)

    execute("""
    ALTER TABLE form_presentation_elements ADD CONSTRAINT form_presentation_elements_position_unique UNIQUE (version_id, position) DEFERRABLE INITIALLY IMMEDIATE;
    """)

    execute("""
    ALTER TABLE form_labels ADD CONSTRAINT form_labels_position_unique UNIQUE (label_set_id, position) DEFERRABLE INITIALLY IMMEDIATE;
    """)
  end

  def down do
    execute("""
    ALTER TABLE form_labels DROP CONSTRAINT form_labels_position_unique;
    """)

    execute("""
    ALTER TABLE form_presentation_elements DROP CONSTRAINT form_presentation_elements_position_unique;
    """)

    execute("""
    ALTER TABLE form_question_options DROP CONSTRAINT form_question_options_position_unique;
    """)

    execute("""
    ALTER TABLE form_labels ADD CONSTRAINT form_labels_position_unique UNIQUE (label_set_id, position) DEFERRABLE INITIALLY DEFERRED;
    """)

    execute("""
    ALTER TABLE form_presentation_elements ADD CONSTRAINT form_presentation_elements_position_unique UNIQUE (version_id, position) DEFERRABLE INITIALLY DEFERRED;
    """)

    execute("""
    ALTER TABLE form_question_options ADD CONSTRAINT form_question_options_position_unique UNIQUE (question_id, position) DEFERRABLE INITIALLY DEFERRED;
    """)
  end
end
